// // object model for each resource
// {
//     programName: "",
//     spa: "",
//     operator: "",
//     city: "",
//     address: "",
//     website: "",
//     phone: "",
//     hours: "",
//     walkIn: boolean,
//     eligibility: ""
// }

const centers = [[
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "American Recovery Center ",
    "Neighborhood": "Pomona",
    "Address": "2180 West Valley Boulevard\n\nPomona CA 91768\n\n",
    "Website": "",
    "Email": "",
    "Phone": "(909) 865-2336",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 8 - South Bay",
    "Operator": "American Recovery Center ",
    "Neighborhood": "Long Beach",
    "Address": "1334 Alamitos Ave Long Beach, CA 90813",
    "Website": "",
    "Email": "",
    "Phone": "(562) 218-2355",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "American Recovery Center ",
    "Neighborhood": "Pasadena",
    "Address": "56 W. Del Mar Blvd.\n\nPasadena, CA 91105\n\n",
    "Website": "",
    "Email": "",
    "Phone": "(626) 577-4649",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 5 - West LA",
    "Operator": "American Recovery Center ",
    "Neighborhood": "Santa Monica",
    "Address": "1658 11th St\n\nSanta Monica, CA 90404\n\n",
    "Website": "",
    "Email": "",
    "Phone": "(310) 450-7235",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 2 - San Clarita Valley",
    "Operator": "American Recovery Center ",
    "Neighborhood": "Canoga Park",
    "Address": "21375 Roscoe Blvd.\n\nCanoga Park, CA 91304\n\n",
    "Website": "",
    "Email": "",
    "Phone": "(818) 883-5527",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 7 - South East LA",
    "Operator": "Salvation Army- Bell Shelter",
    "Neighborhood": "Bell",
    "Address": "5600 Richenbacker Rd.\n\nBldg 2A-2B Bell, CA 90201",
    "Website": "",
    "Email": "",
    "Phone": "(323) 263-1206 ",
    "Hours of Operation": "Call Mon – Fri at 9:00 a.m",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": "Referral perferred"
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 4 - Metro LA",
    "Operator": "",
    "Neighborhood": "Rampart Village",
    "Address": "155 South Bimini Place \nLos Angeles, California 90004\n",
    "Website": "",
    "Email": "",
    "Phone": "(213) 388-5423",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": "Long Term Residential\n\nSliding Scale\n\n"
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Aurora Behavioral Health Care- Charter Oak",
    "Neighborhood": "Covina",
    "Address": "1161 E. Covina Blvd Covina, CA 91724",
    "Website": "https://www.charteroakhospital.com/",
    "Email": "",
    "Phone": "(626) 996-1632",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "",
    "Operator": "First House",
    "Neighborhood": "",
    "Address": "",
    "Website": "",
    "Email": "",
    "Phone": "(949) 515-2360",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": "No Further information "
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 5 - West LA",
    "Operator": "Clare Foundation",
    "Neighborhood": "Santa Monica",
    "Address": "909 Pico Blvd, Santa Monica, CA 90405",
    "Website": "https://clarefoundation.org/",
    "Email": "",
    "Phone": "(310) 314-6245",
    "Hours of Operation": "24 Hours",
    "Walk Ins Allowed?": "Yes",
    "Eligibility Requirements": "Call to schedule an appointment ",
    "Notes": "No Further information "
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 7 - South East LA",
    "Operator": "",
    "Neighborhood": "Norwalk",
    "Address": "11401 Bloomfield Avenue\nBuildings 209, 211 and 313\nNorwalk CA 90650\n",
    "Website": "https://www.intherooms.com/Rehabs/CA/Norwalk/Southern_CA_Alcohol_and_Drug_Progs_Inc_1069.php",
    "Email": "",
    "Phone": "(562) 864-7724",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "Didi Hirsch CMHC Via Avanta Program",
    "Service Planning Geographic Area": "SPA 2 - San Clarita Valley",
    "Operator": "Didi Hirsch Mental Health",
    "Neighborhood": "Pacoima",
    "Address": "11643 Glenoaks Blvd. Pacoima, CA 91331\n\n",
    "Website": "https://didihirsch.org/",
    "Email": "",
    "Phone": "(818) 897-2609 ",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Grandview Foundation",
    "Neighborhood": "Pasadena",
    "Address": "1230 N Marengo Ave Pasadena, CA 91114\n",
    "Website": "https://grandviewfoundation.com/",
    "Email": "",
    "Phone": "(626) 797-1124",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": "Call for intake process"
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 6 - Central LA",
    "Operator": "His Sheltering Arms",
    "Neighborhood": "South Los Angeles",
    "Address": "11101 S Main St\n\nLos Angeles, CA 90061",
    "Website": "",
    "Email": "",
    "Phone": "(323) 755-6646",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 2 - San Clarita Valley",
    "Operator": "People in Progress Sun Valley Community Rehab Center",
    "Neighborhood": "Sun Valley",
    "Address": "8140 Sunland Boulevard\n\nSun Valley CA 91352\n\n",
    "Website": "",
    "Email": "",
    "Phone": "(818) 768-7494",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 4 - Metro LA",
    "Operator": "Rena B. Recovery Center",
    "Neighborhood": "East Hollywood",
    "Address": "4445 Burns Ave, Los Angeles, CA 90029",
    "Website": "",
    "Email": "",
    "Phone": "(323) 664-8940",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": "100 beds, Call for Intake Process"
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 4 - Metro LA",
    "Operator": "Royal Palms Recovery Center (Albert)",
    "Neighborhood": "Historic Filipinotown",
    "Address": "360 S Westlake Ave, Los Angeles, CA 90057",
    "Website": "",
    "Email": "",
    "Phone": "",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": "(135 beds), Call for intake process"
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "River Community Recovery",
    "Neighborhood": "Azuza",
    "Address": "23701 E Fork Rd, Azusa, CA 91702",
    "Website": "http://losangeles.networkofcare.org/mh/services/agency.aspx?pid=SOCIALMODELRECOVERYSYSTEMSTHERIVERCOMMUNITYAZUSA_68_2_0",
    "Email": "",
    "Phone": "(626) 910.-1202",
    "Hours of Operation": "MON - FRI 9:00 AM - 5:00 PM",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 8 - South Bay",
    "Operator": "Substance Abuse Foundation",
    "Neighborhood": "Long Beach",
    "Address": "3125 E 7th St Long Beach CA 90804",
    "Website": "http://asaferefuge.org/",
    "Email": "",
    "Phone": "(562) 987-5742",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 2 - San Clarita Valley",
    "Operator": "Tarzana Treatment Center",
    "Neighborhood": "Tarzana",
    "Address": "18646 Oxnard St Tarzana, CA",
    "Website": "https://www.tarzanatc.org/",
    "Email": "",
    "Phone": "(800) 996-1051",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "",
    "Operator": "Red Gate ",
    "Neighborhood": "",
    "Address": "",
    "Website": "",
    "Email": "",
    "Phone": "(562) 599-8444",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": "No further information "
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 4 - Metro LA",
    "Operator": "Volunteers Of America Detox \n\n(Drop in Center)\n\n",
    "Neighborhood": "Downtown Los Angeles",
    "Address": "543 Crocker St\nLos Angeles, CA 90013  \n",
    "Website": "https://voala.org/",
    "Email": "",
    "Phone": "(213) 236-0874",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 4 - Metro LA",
    "Operator": "Walden House\n\nTransitional Treatment Center\n\n",
    "Neighborhood": "Fashion District",
    "Address": " 1355 South Hill Street Los Angeles CA 90015",
    "Website": "",
    "Email": "",
    "Phone": "(213) 763-6220",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Walter Hoving Home",
    "Neighborhood": "Pasadena",
    "Address": "127 S El Molino Ave  \n\nPasadena, CA 91101\n\n",
    "Website": "https://hovinghome.org/",
    "Email": "",
    "Phone": "(626) 405-0950",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "Warm Springs Rehabilitation Center",
    "Service Planning Geographic Area": "SPA 2 - San Clarita Valley",
    "Operator": "Antelope Valley Rehabilitation Centers",
    "Neighborhood": "Castaic",
    "Address": "38200 North Lake Hughes Road\n\nCastaic CA 91310\n\n",
    "Website": "",
    "Email": "",
    "Phone": "(661) 257-2342",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "",
    "Service Planning Geographic Area": "SPA 4 - Metro LA",
    "Operator": "Weingart Center",
    "Neighborhood": "Downtown Los Angeles",
    "Address": "566 South San Pedro Street\n\nLos Angeles, CA 90013\n\n",
    "Website": "",
    "Email": "",
    "Phone": "(213) 627-9000.",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "Exodus Recovery, Inc.",
    "Service Planning Geographic Area": "SPA 8 - South Bay",
    "Operator": "Exodus Recovery, Inc.",
    "Neighborhood": "Redondo Beach",
    "Address": "923 South Catalina Avenue Redondo Beach, CA, 90277",
    "Website": "",
    "Email": "",
    "Phone": "800-286-1182",
    "Hours of Operation": "Monday through Friday 9:00 a.m. to 5:00 p.m",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "ages of 26-59 only",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "Drug and Alcohol Program",
    "Service Planning Geographic Area": "SPA 7 - South East LA",
    "Operator": "Positive Steps",
    "Neighborhood": "Downey",
    "Address": "11501 Dolan Ave., Downey, CA 90241",
    "Website": "",
    "Email": "",
    "Phone": "562-923-7894",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": "Alcohol and drug programs for men"
},
{
    "Updated by SPA leadership": "",
    "Program Name": "Drug and Alcohol Program",
    "Service Planning Geographic Area": "SPA 7 - South East LA",
    "Operator": "Little House",
    "Neighborhood": "Bellflower",
    "Address": "9718 Harvard St., Bellflower, CA 90706",
    "Website": "",
    "Email": "",
    "Phone": "562-925-2777",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": "Recovery home for women with substance abuse"
},
{
    "Updated by SPA leadership": "",
    "Program Name": "Substance abuse program",
    "Service Planning Geographic Area": "SPA 7 - South East LA",
    "Operator": "Los Angeles Center for Alcohol and Drug Abuse",
    "Neighborhood": "Santa Fe Springs",
    "Address": "11015 Bloomfield Ave, Santa Fe Springs, CA 90670",
    "Website": "http://www.lacada.com/",
    "Email": "",
    "Phone": "562-906-2676",
    "Hours of Operation": "",
    "Walk Ins Allowed?": "",
    "Eligibility Requirements": "",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "LA County Dept. of Mental Health",
    "Service Planning Geographic Area": "SPA 1 - Antelope Valley",
    "Operator": "LACDMH",
    "Neighborhood": "Palmdale",
    "Address": "1529 E. Palmdale Blvd., Ste. 150 Palmdale, CA 93550",
    "Website": "dmh.lacounty.gov",
    "Email": "",
    "Phone": "(800) 854-7771",
    "Hours of Operation": "Monday through Sunday, 24 hours per day",
    "Walk Ins Allowed?": "Yes",
    "Eligibility Requirements": "TAY, Family, Adult",
    "Notes": ""
},
{
    "Updated by SPA leadership": "",
    "Program Name": "Tarzana Treatment Center",
    "Service Planning Geographic Area": "SPA 1 - Antelope Valley",
    "Operator": "Tarzana Treatment Center",
    "Neighborhood": "Lancaster",
    "Address": "44447 10th St W, Lancaster, CA 93534",
    "Website": "",
    "Email": "",
    "Phone": "(661) 726-2630",
    "Hours of Operation": "Monday - Friday 8:00 AM - 5:00 PM",
    "Walk Ins Allowed?": "No",
    "Eligibility Requirements": "",
    "Notes": ""
}]]