const groceries = [
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
        OPERATOR: "All Saints Episcopal Church",
        NEIGHBORHOOD: "Pasadena",
        ADDRESS: "132 N Euclid Ave Pasadena, CA 91101",
        WEBSITE: "https://allsaints-pas.org/",
        EMAIL: "N/A",
        PHONE_NUMBER: "(626) 796-1172",
        HOURS_OF_OPERATION: "Monday, 9am-12pm & 1-3:30pm",
        WALK_IN: "No",
        ELIGIBILITY_REQUIREMENTS: "Call to inquire about eligibility",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
        OPERATOR: "First Church of the Nazarene",
        NEIGHBORHOOD: "Pasadena",
        ADDRESS: "3700 E. Sierra Madre Blvd.",
        WEBSITE: "https://www.paznaz.org/",
        EMAIL: "info@paznaz.org",
        PHONE_NUMBER: "(626) 351-9631",
        HOURS_OF_OPERATION: "Wednesday & Thursday 2-4pm (once / 2wk)",
        WALK_IN: "No",
        ELIGIBILITY_REQUIREMENTS: "Call to inquire about eligibility",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
        OPERATOR: "Foothill Unity Center",
        NEIGHBORHOOD: "Pasadena",
        ADDRESS: "191 N. Oak Ave Pasadena CA 91107",
        WEBSITE: "http://foothillunitycenter.org/",
        EMAIL: "N/A",
        PHONE_NUMBER: "(626) 584-7420",
        HOURS_OF_OPERATION: "Tuesday 9-11:30a,. Wednesday & Friday 1-3:30pm. (once/wk)",
        WALK_IN: "No",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
        OPERATOR: "Friends in Deed",
        NEIGHBORHOOD: "Pasadena",
        ADDRESS: "444 E Washington Blvd, Pasadena, CA 91104",
        WEBSITE: "http://friendsindeedpas.org/fid/",
        EMAIL: "N/A",
        PHONE_NUMBER: "(626) 797-5335",
        HOURS_OF_OPERATION: "Tues & Wed, 10am-3p (once/wk",
        WALK_IN: "No",
        ELIGIBILITY_REQUIREMENTS: "Call to inquire about eligibility",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
        OPERATOR: "Lincoln Avenue Baptist Church ",
        NEIGHBORHOOD: "Pasadena",
        ADDRESS: "1180 Lincoln Avenue Pasadena, CA 91103",
        WEBSITE: "http://www.lincolnavenuechristianchurch.org/",
        EMAIL: "Contactus@labcpasadena.org",
        PHONE_NUMBER: "(626) 798-9163",
        HOURS_OF_OPERATION: "Wednesday 10am",
        WALK_IN: "No",
        ELIGIBILITY_REQUIREMENTS: "Call to inquire about eligibility",
    },
    {
        PROGRAM_NAME: "Free groceries and food vouchers",
        SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
        OPERATOR: "Salvation Army",
        NEIGHBORHOOD: "Pasadena",
        ADDRESS: "1000 E Walnut St Ste 102, Pasadena, CA 91106",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(626) 773-4404",
        HOURS_OF_OPERATION: "Monday-Friday 9-11:30am",
        WALK_IN: "No",
        ELIGIBILITY_REQUIREMENTS: "Call to inquire about eligibility",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 4 - Metro LA",
        OPERATOR: "First Church of the Nazarene",
        NEIGHBORHOOD: "Rampart Village",
        ADDRESS: "3401 W 3rd St Los Angeles",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(213) 276-4600",
        HOURS_OF_OPERATION: "N/A",
        WALK_IN: "No",
        ELIGIBILITY_REQUIREMENTS: "Line begins at 8am/First come first serve",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "Harbor Interfaith Services ",
        NEIGHBORHOOD: "San Pedro",
        ADDRESS: "670 W. 9th Street, San Pedro",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 831-9123",
        HOURS_OF_OPERATION: "Monday-Friday, 9-11:30A, 1-5PM",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "Toberman Neighborhood Ctr",
        NEIGHBORHOOD: "San Pedro",
        ADDRESS: "131 N. Grand Ave, San Pedro",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 832-1145 x106",
        HOURS_OF_OPERATION: "9-5, except 12-1. A-L Last Names T/TH; M-Z Last Names M-F; All on F",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "1st-15th: can come once/week; 16th-end of month: 2x/week",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "Food Net-San Pedro Service Center",
        NEIGHBORHOOD: "San Pedro",
        ADDRESS: "769 W. 3rd St, San Pedro, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 519-6091",
        HOURS_OF_OPERATION: "Tuesday-Thursday, 2-4:30P",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "St. Peter & Paul Church",
        NEIGHBORHOOD: "Wilmington",
        ADDRESS: "736 N. Lagoon Ave, Wilmington, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 834-5215",
        HOURS_OF_OPERATION: "Monday, Tuesday, Thursday; 10am",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "St. Margaret’s Center",
        NEIGHBORHOOD: "Lennox",
        ADDRESS: "10217 Inglewood, Lennox",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 672-2208",
        HOURS_OF_OPERATION: "Monday, Wednesday, Friday 9-12p, 1-4p",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "Serves residents in Inglewood, Lennox, Hawthorne, Lawndale, El Segundo, Manhattan Beach, Gardena, LA City in 90045, 90047 zip codes.Call first, same-day appt’s available",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "St. Andrew’s Presbyterian Church",
        NEIGHBORHOOD: "Redondo Beach",
        ADDRESS: "301 Avenue D, Redondo Beach, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 540-5252",
        HOURS_OF_OPERATION: "Tuesday & Thursday, 12-1pm ",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "First 100 guests in the serves Lawndale, Lennox, Inglewood, Westchester, El Segundo, parts of LA.   ",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "Food Pantry LAX",
        NEIGHBORHOOD: "Inglewood",
        ADDRESS: "355 E. Beach St, Inglewood, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 677-5597",
        HOURS_OF_OPERATION: "Tuesday & Thursday, 10-noon",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "Can get emergency food once a week.",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "Hope In Action",
        NEIGHBORHOOD: "Hermosa Beach",
        ADDRESS: "2420 PCH, Hermosa Beach, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 374-4673",
        HOURS_OF_OPERATION: "Monday & Wednesday 9a-12pm",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "Non-church members can get groceries once/month",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "St. Philomena Catholic Church",
        NEIGHBORHOOD: "Carson",
        ADDRESS: "21900 S. Main St, Carson, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 835-7161",
        HOURS_OF_OPERATION: "Tuesday 7:30-9:30A",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "Services Carson residents only",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "Harbor Gateway/Torrance Outreach",
        NEIGHBORHOOD: "Torrance",
        ADDRESS: "22400 S. Halldale, Ave, Torrance, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 328-3689",
        HOURS_OF_OPERATION: "2nd and 4th Tuesday 9:30am",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "serves Torrance, Lomita, Gardena, Carson, Harbor G’Way",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "St. Margaret Mary Catholic Parish",
        NEIGHBORHOOD: "Lomita",
        ADDRESS: "25511 Eshelman, Lomita, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 326-3364 x15",
        HOURS_OF_OPERATION: "8:30-10:00am",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "serves Lomita, Wilmington, Harbor City, Torrance residents",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "Calvary Light Christian Center",
        NEIGHBORHOOD: "Wilmington",
        ADDRESS: "1101 N. Lakme Ave, Wilmington, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 830-3043",
        HOURS_OF_OPERATION: "Wednesday 2-3:30pm",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "Crenshaw Baptist Church",
        NEIGHBORHOOD: "Torrance",
        ADDRESS: "18749 Crenshaw Blvd, Torrance, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 323-2115",
        HOURS_OF_OPERATION: "2nd Wednesday 8-10:30am",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "St. Paul’s United Methodist",
        NEIGHBORHOOD: "Redondo Beach",
        ADDRESS: "2600 Nelson, Redondo Beach, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 370-4319",
        HOURS_OF_OPERATION: "1st and 3rd Thursday 9-11am",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "Calvary Assembly of God",
        NEIGHBORHOOD: "Lomita",
        ADDRESS: "25501 Oak St, Lomita, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 326-2757",
        HOURS_OF_OPERATION: "2nd, 4th Thursday, 6-7pm",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "Oceangate Baptist",
        NEIGHBORHOOD: "Hawthorne",
        ADDRESS: "13443 Oceangate Ave., Hawthorne, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 973-7031",
        HOURS_OF_OPERATION: "Thursday 1-4pm",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "Salvation Army",
        NEIGHBORHOOD: "San Pedro",
        ADDRESS: "138 S. Bandini St, San Pedro, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 832-7228",
        HOURS_OF_OPERATION: "Thursday 9am-12pm",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "Can receive groceries once a month",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "Del Aire Baptist Church",
        NEIGHBORHOOD: "Hawthorne",
        ADDRESS: "4951 W. 119th Pl, Hawthorne, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 676-8352",
        HOURS_OF_OPERATION: "Friday 9am-1pm",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "Vermont Ave Baptist Church",
        NEIGHBORHOOD: "Torrance",
        ADDRESS: "23325 S. Vermont Ave, Torrance, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 530-0533",
        HOURS_OF_OPERATION: "3rd Saturday 10-11am",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "Rock Solid Christian Assembly",
        NEIGHBORHOOD: "San Pedro",
        ADDRESS: "275 W. 1st St, San Pedro, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 832-2788",
        HOURS_OF_OPERATION: "2nd, 4th Saturday 10:30-11:30am",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "Warren Chapel CME Church",
        NEIGHBORHOOD: "San Pedro",
        ADDRESS: "1039 W. Elberon Ave, San Pedro, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 547-5362",
        HOURS_OF_OPERATION: "2nd, 4th Saturday 1-3pm",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "Calvary Hawthorne Presbyterian Church",
        NEIGHBORHOOD: "Hawthorne",
        ADDRESS: "13560 Hawthorne Blvd, Hawthorne, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 676-1144",
        HOURS_OF_OPERATION: "1st Saturday 11:00a",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "Hope Chapel",
        NEIGHBORHOOD: "Hawthorne",
        ADDRESS: "13560 Hawthorne Blvd Hawthorne ",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 970-9023",
        HOURS_OF_OPERATION: "3rd Sat. 12-12:30",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "First Christian Church of Wilmington",
        NEIGHBORHOOD: "Wilmington",
        ADDRESS: "444 E. Lomita Blvd, Wilmington",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 835-4114",
        HOURS_OF_OPERATION: "4th Sat 9-11:30a",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "Holy Trinity Lutheran",
        NEIGHBORHOOD: "Inglewood",
        ADDRESS: "9300 S. Crenshaw, Inglewood, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(323) 757-1739",
        HOURS_OF_OPERATION: "2nd, 4th Saturday 1-2pm",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "St. Lawrence Martyr Catholic Church",
        NEIGHBORHOOD: "Redondo Beach",
        ADDRESS: "1900 S Prospect Ave., Redondo Beach, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 540-0329",
        HOURS_OF_OPERATION: "1st Saturday 8:30-10am",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "Numbers are drawn randomly at 7:55 am for food distribution rather than on a first come-first serve basis",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "St. Joseph Catholic Church",
        NEIGHBORHOOD: "Hawthorne",
        ADDRESS: "11886 S. Acacia Ave, Hawthorne",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 679-1139",
        HOURS_OF_OPERATION: "2nd Sunday 8a-12:30p",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
        OPERATOR: "House of Yahweh",
        NEIGHBORHOOD: "Lawndale",
        ADDRESS: "4046 Marine Ave., Lawndale, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 675-1384",
        HOURS_OF_OPERATION: "N/A",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "Apply for Food Outreach at office; if qualified, pick up food once/week from 2-3p; Emergency Food once/month call 310-675-1384 from 9-10a; first 10 calle(rs") 
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 6 - Central LA",
        OPERATOR: "Compton College Food Pantry ",
        NEIGHBORHOOD: "Compton",
        ADDRESS: " 1111 E Artesia Blvd, Compton, CA 90221",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 660-9000",
        HOURS_OF_OPERATION: "N/A",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Free groceries ",
        SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
        OPERATOR: "God Provides Ministry ",
        NEIGHBORHOOD: "South El Monte",
        ADDRESS: "2453 TROY AVE SOUTH EL MONTE, CA 91733",
        WEBSITE: "http://www.godprovidesministry.org/",
        EMAIL: "N/A",
        PHONE_NUMBER: "(626) 442-4273",
        HOURS_OF_OPERATION: "Monday-Friday 8AM to 4PM, Saturday 8AM to 2PM",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "Call for eligibility requirements",
    },
    {
        PROGRAM_NAME: "Grace Resources - Free Groceries",
        SERVICE_PLANNING_AREA: "SPA 1 - Antelope Valley",
        OPERATOR: "Grace Resources",
        NEIGHBORHOOD: "Lancaster",
        ADDRESS: "Grace Resource Ctr. 45134 Sierra Hwy., Lancaster, CA",
        WEBSITE: "https://www.graceresources.org/",
        EMAIL: "N/A",
        PHONE_NUMBER: "(661) 940-5272",
        HOURS_OF_OPERATION: "Tuesdays & Thursdays at 10:00 AM & 1:00 PM; Spanish only on Wednesdays at 10:00 AM",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Lancaster Baptist - Groceries",
        SERVICE_PLANNING_AREA: "SPA 1 - Antelope Valley",
        OPERATOR: "Lancaster Baptist Church",
        NEIGHBORHOOD: "Lancaster",
        ADDRESS: "First Baptist Church, 603 E. Lancaster Blvd, Lancaster, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "N/A",
        HOURS_OF_OPERATION: "Saturday at 9:00 AM",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
        OPERATOR: "St. Bernard Church Food Pantry",
        NEIGHBORHOOD: "Belflower",
        ADDRESS: "9627 Beach St., Bellflower, CA ",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(562) 867-2337",
        HOURS_OF_OPERATION: "Tuesday 10:00 AM - 1:00 PM",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
        OPERATOR: "Salvation Army",
        NEIGHBORHOOD: "Belflower",
        ADDRESS: "9644 Cedar St, Bellflower, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(562) 804-0808",
        HOURS_OF_OPERATION: "Tuesday 9:00 AM  - 12:00 PM",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
        OPERATOR: "Bethany Church",
        NEIGHBORHOOD: "Belflower",
        ADDRESS: "17054 Bixby Ave, Bellflower, CA ",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(562) 866-1812",
        HOURS_OF_OPERATION: "Tuesday 2:00 PM  - 3:00 PM, 4:00 PM - 5:00 PM",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
        OPERATOR: "The Lord's Church",
        NEIGHBORHOOD: "Belflower",
        ADDRESS: "9740 Flower St, Bellflower, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(562) 866-8283",
        HOURS_OF_OPERATION: "2nd and 4th Wednesday 7:45 PM",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
        OPERATOR: "Angel City Cafe",
        NEIGHBORHOOD: "Belflower",
        ADDRESS: "16507 Bellflower Blvd, Bellflower, CA ",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(562) 204-6461",
        HOURS_OF_OPERATION: "2nd and 4th Wednesday 11:30 AM - 1:30 PM",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
        OPERATOR: "Hosanna Chapel of Bellflower",
        NEIGHBORHOOD: "Belflower",
        ADDRESS: "16517 S. Bellflower Blvd, Bellflower, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(562) 925-5093",
        HOURS_OF_OPERATION: "Wednesday-Thursday 8:30 PM - 9:00 PM ",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
        NOTES: "Food is distributed after Bible Study 7:15PM"
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
        OPERATOR: "St. Dominic Savio Church, Bellflower, CA",
        NEIGHBORHOOD: "Belflower",
        ADDRESS: "13400 Bellflower Blvd., Bellflower, CA ",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(562) 920-7796",
        HOURS_OF_OPERATION: "Thursday 8:00 AM - 10:00 AM",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
        NOTES: "Canned food, meat and bread"
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
        OPERATOR: "Bellwood Baptist Church",
        NEIGHBORHOOD: "Belflower",
        ADDRESS: "17614 Virginia Ave., Bellflower, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(562) 925-4888",
        HOURS_OF_OPERATION: "Thursday 10:00 AM",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
        OPERATOR: "Cityline",
        NEIGHBORHOOD: "Belflower",
        ADDRESS: "3936 Woodruff Ave., Bellflower, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(562) 421-9374",
        HOURS_OF_OPERATION: "4th Thursday 10:00 AM - 11:00 AM",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
        OPERATOR: "St. George's Church",
        NEIGHBORHOOD: "Belflower",
        ADDRESS: "15721 Cornuta Ave., Bellflower, CA ",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(562) 925-3706",
        HOURS_OF_OPERATION: "2nd and 4th Tuesday 4:00PM - 6:00 PM",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
        OPERATOR: "Holy Redeemer Lutheran",
        NEIGHBORHOOD: "Belflower",
        ADDRESS: "14515 Blaine Ave., Bellflower, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(562) 867-0714",
        HOURS_OF_OPERATION: "Friday 9:00 AM - 10:30 AM",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
        NOTES: "Sign in at 8:00 AM"
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
        OPERATOR: "Rosewood Church",
        NEIGHBORHOOD: "Belflower",
        ADDRESS: "10115 Rose St., Bellflower, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(562) 804-4778",
        HOURS_OF_OPERATION: "Friday 3:00 PM - 4:00 PM",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
        OPERATOR: "The Journey @ Mayfair Church",
        NEIGHBORHOOD: "Lakewood",
        ADDRESS: "6150 Bellflower Blvd, Lakewood, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(562) 867-3198",
        HOURS_OF_OPERATION: "1st Saturday 9:00 AM - 11:00AM",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
        OPERATOR: "Lakewood First United Methodist",
        NEIGHBORHOOD: "Belflower",
        ADDRESS: "4300 Bellflower Blvd., Bellflower, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(562) 425-1219",
        HOURS_OF_OPERATION: "2nd and 4th Saturday 9:00 AM - 11:00 AM",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
        OPERATOR: "Hosanna Chapel of Bellflower",
        NEIGHBORHOOD: "Belflower",
        ADDRESS: "16517 S Bellflower Blvd, Bellflower, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(562) 925-5093",
        HOURS_OF_OPERATION: "Sunday 11:45 AM - 12:30 PM",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Bank",
        SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
        OPERATOR: "Hawaiian Gardens Food Bank",
        NEIGHBORHOOD: "Hawaiian Gardens",
        ADDRESS: "2212 Norwalk Blvd, Hawaiian Gardens, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(562) 860-9097",
        HOURS_OF_OPERATION: "Wednesdat 2:00 PM - 6:00 PM, thursday 9:30 AM - 3:30 PM",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
        OPERATOR: "Calvary Chapel",
        NEIGHBORHOOD: "Downey",
        ADDRESS: "12808 Woodruff Ave, Downey, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(562) 803-5631",
        HOURS_OF_OPERATION: "Mon, Wed, Fri 9:30AM 1:30PM",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Ministry",
        SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
        OPERATOR: "Calvary Chapel",
        NEIGHBORHOOD: "Downey",
        ADDRESS: "12808 Woodruff Ave, Downey, CA",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(562) 803-5631",
        HOURS_OF_OPERATION: "Tuesday 7:30PM - 8:30PM, Wednesday 4:00 PM - 7:00 PM, Saturday 9:00 PM - 1:00 PM, Sunday 9:30AM - 10:30AM",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Bank",
        SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
        OPERATOR: "Lawrence Ministries",
        NEIGHBORHOOD: "Hawaiian Gardens",
        ADDRESS: "12441 E Farlow St, Hawaiian Gardens, CA ",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "(562) 653-9868",
        HOURS_OF_OPERATION: "3rd Saturday 10:00 AM - 2:00 PM",
        WALK_IN: "Yes",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
        OPERATOR: "Cory's Kitchen - Irwindale Warehouse",
        NEIGHBORHOOD: "Irwindale",
        ADDRESS: "1418 Arrow Hwy Irwindale, CA 91706",
        WEBSITE: "https://www.coryskitchen.org/",
        EMAIL: "N/A",
        PHONE_NUMBER: "(626) 305-0392",
        HOURS_OF_OPERATION: "Tuesdays 5:30PM to 7:30PM",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "Photo ID and two proofs of residence",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
        OPERATOR: "Cory's Kitchen - Baldwin Park New Beginnings",
        NEIGHBORHOOD: "Baldwin Park",
        ADDRESS: "13020 Francisquito Ave. Baldwin Park, CA 91706",
        WEBSITE: "https://www.coryskitchen.org/",
        EMAIL: "N/A",
        PHONE_NUMBER: "(626) 331-3322",
        HOURS_OF_OPERATION: "Fridays 5:00PM to 7:00PM",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "Photo ID and two proofs of residence",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
        OPERATOR: "Inland Valley Hope Partners- Beta Program Center",
        NEIGHBORHOOD: "Pomona",
        ADDRESS: "1095 W. Grand Ave. Pomona, CA 91766 ",
        WEBSITE: "http://www.inlandvalleyhopepartners.org/Program-Services/Food-Security-Program.asp",
        EMAIL: "N/A",
        PHONE_NUMBER: "(909) 622-3806, x#301 ",
        HOURS_OF_OPERATION: "Monday – Thursday  9:00 a.m. – 3:00 p.m",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
        OPERATOR: "Inland Valley Hope Partners- San Dimas Center",
        NEIGHBORHOOD: "San Dimas",
        ADDRESS: "110 E. Third Street San Dimas, CA 91773 ",
        WEBSITE: "http://www.inlandvalleyhopepartners.org/Program-Services/Food-Security-Program.asp",
        EMAIL: "N/A",
        PHONE_NUMBER: "(909) 599-1103",
        HOURS_OF_OPERATION: "Monday, Wednesday, Fri. 2:00 – 4:00 p.m.",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
        OPERATOR: "Inland Valley Hope Partners- Claremont Center",
        NEIGHBORHOOD: "Claremont",
        ADDRESS: "660 N. Mountain Ave Claremont, CA 91711",
        WEBSITE: "http://www.inlandvalleyhopepartners.org/Program-Services/Food-Security-Program.asp",
        EMAIL: "N/A",
        PHONE_NUMBER: "(909) 622-3806, x#401",
        HOURS_OF_OPERATION: "Tuesday & Thursday 12:30 - 4:30",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
        OPERATOR: "Inland Valley Hope Partners- Urban Mission Center",
        NEIGHBORHOOD: "Pomona",
        ADDRESS: "810 South White  Pomona, CA 91768 ",
        WEBSITE: "http://www.inlandvalleyhopepartners.org/Program-Services/Food-Security-Program.asp",
        EMAIL: "N/A",
        PHONE_NUMBER: "(909) 622-3806",
        HOURS_OF_OPERATION: "Thursday 9:30 a.m. – 3:30 p.m",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
        OPERATOR: "Shepherd's Pantry",
        NEIGHBORHOOD: "Glendora",
        ADDRESS: "657 E. Arrow Highway, Ste J Glendora, CA 91740 ",
        WEBSITE: "https://www.shepherdspantry.com/services/",
        EMAIL: "N/A",
        PHONE_NUMBER: "(626) 852-7630",
        HOURS_OF_OPERATION: "Wednesday & Thursday 5:00PM to 7:00PM",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
        OPERATOR: "San Gabriel Mission Food Pantry",
        NEIGHBORHOOD: "San Gabriel",
        ADDRESS: "428 S. Mission Drive, San Gabriel, CA 91776",
        WEBSITE: "https://parish.sangabrielmissionchurch.org/apps/events/2014/6/29/1647970/?id=1",
        EMAIL: "N/A",
        PHONE_NUMBER: "(626) 457-3035",
        HOURS_OF_OPERATION: "Sunday 8am – 10am",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
        OPERATOR: "Fountain of Love Church - Community Development Center ",
        NEIGHBORHOOD: "Pomona",
        ADDRESS: "188 W. Orange Grove Ave. Pomona, CA ",
        WEBSITE: "N/A",
        EMAIL: "N/A",
        PHONE_NUMBER: "N/A",
        HOURS_OF_OPERATION: "Tuesday, Wednesday and Thursday 10:00 am to 2:00 pm",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 5 - West LA",
        OPERATOR: "Church on Pearl Pantry",
        NEIGHBORHOOD: "Santa Monica",
        ADDRESS: "1520 Pearl Street, Santa Monica, CA 90405",
        WEBSITE: "http://www.westsidefoodbankca.org/",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 828-6016",
        HOURS_OF_OPERATION: "Wednesday 2:30pm-5:30pm ",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 5 - West LA",
        OPERATOR: "Delaware Ave. SDA Pantry",
        NEIGHBORHOOD: "Santa Monica",
        ADDRESS: "1845 20th Street, Santa Monica, CA 90404",
        WEBSITE: "http://www.westsidefoodbankca.org/",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 450-0919",
        HOURS_OF_OPERATION: "Sunday 12:30pm-1:30pm",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 5 - West LA",
        OPERATOR: "St. Anne's Social Service",
        NEIGHBORHOOD: "Santa Monica",
        ADDRESS: "2013 Colorado Ave, Santa Monica, CA 90404",
        WEBSITE: "https://foodoasis.la/food-pantry/wsfb-st-annes-social-service/",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 824-4411",
        HOURS_OF_OPERATION: "Wednesday 4:00pm-5:30pm ",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 5 - West LA",
        OPERATOR: "St. Joseph Center",
        NEIGHBORHOOD: "Venice",
        ADDRESS: "204 Hampton Drive, Los Angeles, CA 90401",
        WEBSITE: "https://stjosephctr.org/education-vocation-training/",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 396-6468 x313 ",
        HOURS_OF_OPERATION: "Monday, Wednesday, Thursday 10:00am-12:00pm and Tuesday and Friday 1:00pm- 3:00pm",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution",
        SERVICE_PLANNING_AREA: "SPA 5 - West LA",
        OPERATOR: "Salvation Army, Santa Monica",
        NEIGHBORHOOD: "Santa Monica",
        ADDRESS: "1533 4th Street, Santa Monica, CA 90401",
        WEBSITE: "http://www.westsidefoodbankca.org/index.php?option=com_content&task=view&id=70&Itemid=94",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 451-1358",
        HOURS_OF_OPERATION: "Monday thru Friday 9:00am - 11:00am ",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    },
    {
        PROGRAM_NAME: "Food Distribution ",
        SERVICE_PLANNING_AREA: "SPA 5 - West LA",
        OPERATOR: "SOVA West ",
        NEIGHBORHOOD: "Pico-Robertson",
        ADDRESS: "8846 W. Pico Blvd, Los Angeles, CA 90035 ",
        WEBSITE: "https://www.jfsla.org/sslpage.aspx?pid=300",
        EMAIL: "N/A",
        PHONE_NUMBER: "(310) 288-0286 (when pantry is open) 818-988-7682",
        HOURS_OF_OPERATION: "Sunday 9:00am-12:00pm (open every Sunday except holiday weekends) Monday thru Thursday 10:00am- 1:30pm ",
        WALK_IN: "N/A",
        ELIGIBILITY_REQUIREMENTS: "N/A",
    }
]
