// object model for each resource
// {
//     programName: "N/A",
//     spa: "N/A",
//     operator: "N/A",
//     city: "N/A",
//     address: "N/A",
//     website: "N/A",
//     phone: "N/A",
//     hours: "N/A",
//     walkIn: boolean,
//     eligibility: "N/A"
// }

const groceries = [
[
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "All Saints Episcopal Church",
    "Neighborhood": "Pasadena",
    "Address": "132 N Euclid Ave\rPasadena, CA 91101",
    "Website": "https://allsaints-pas.org/",
    "Email": "N/A",
    "Phone": "(626) 796-1172",
    "Hours of Operation": "Mon, 9am-12pm & 1-3:30pm",
    "Walk-Ins Allowed?": "No",
    "Eligibility Requirements": "Call to inquire about eligibility",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "First Church of the Nazarene",
    "Neighborhood": "Pasadena",
    "Address": "3700 E. Sierra Madre Blvd.",
    "Website": "https://www.paznaz.org/",
    "Email": "info@paznaz.org",
    "Phone": "(626) 351-9631",
    "Hours of Operation": "Wed & Thurs 2-4pm (once/2wk",
    "Walk-Ins Allowed?": "No",
    "Eligibility Requirements": "Call to inquire about eligibility",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Foothill Unity Center",
    "Neighborhood": "Pasadena",
    "Address": "191 N. Oak Ave Pasadena CA 91107",
    "Website": "http://foothillunitycenter.org/",
    "Email": "N/A",
    "Phone": "(626) 584-7420",
    "Hours of Operation": "Tues 9-11:30a,. Wed & Fri 1-3:30pm. (once/wk)",
    "Walk-Ins Allowed?": "No",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Friends in Deed",
    "Neighborhood": "Pasadena",
    "Address": "444 E Washington Blvd, Pasadena, CA 91104",
    "Website": "http://friendsindeedpas.org/fid/",
    "Email": "N/A",
    "Phone": "(626) 797-5335",
    "Hours of Operation": "Tues & Wed, 10am-3p (once/wk",
    "Walk-Ins Allowed?": "No",
    "Eligibility Requirements": "Call to inquire about eligibility",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Lincoln Avenue Baptist Church ",
    "Neighborhood": "Pasadena",
    "Address": "1180 Lincoln Avenue Pasadena, CA 91103",
    "Website": "http://www.lincolnavenuechristianchurch.org/",
    "Email": "Contactus@labcpasadena.org",
    "Phone": "(626) 798-9163",
    "Hours of Operation": "Wed 10am",
    "Walk-Ins Allowed?": "No",
    "Eligibility Requirements": "Call to inquire about eligibility",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries and food vouchers",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Salvation Army",
    "Neighborhood": "Pasadena",
    "Address": "1000 E Walnut St Ste 102, Pasadena, CA 91106",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "(626) 773-4404",
    "Hours of Operation": "Mon-Fri 9-11:30am",
    "Walk-Ins Allowed?": "No",
    "Eligibility Requirements": "Call to inquire about eligibility",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 4 - Metro LA",
    "Operator": "First Church of the Nazarene",
    "Neighborhood": "Rampart Village",
    "Address": "3401 W 3rd St Los Angeles",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "213-276-4600",
    "Hours of Operation": "N/A",
    "Walk-Ins Allowed?": "No",
    "Eligibility Requirements": "Line begins at 8am/First come first serve",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Harbor Interfaith Services ",
    "Neighborhood": "San Pedro",
    "Address": "670 W. 9th Street, San Pedro",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-831-9123",
    "Hours of Operation": "M-F, 9-11:30A, 1-5PM",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Toberman Neighborhood Ctr",
    "Neighborhood": "San Pedro",
    "Address": "131 N. Grand Ave, San Pedro",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-832-1145 x106",
    "Hours of Operation": "9-5, except 12-1. A-L Last Names T/TH; M-Z Last Names M-F; All on F",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "1st-15th: can come once/week; 16th-end of month: 2x/week",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Food Net-San Pedro Service Center",
    "Neighborhood": "San Pedro",
    "Address": "769 W. 3rd St, San Pedro",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-519-6091",
    "Hours of Operation": "T-Th, 2-4:30P",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "St. Peter & Paul Church",
    "Neighborhood": "Wilmington",
    "Address": "736 N. Lagoon Ave, Wilmington",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-834-5215",
    "Hours of Operation": "M, T, TH; 10am",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "St. Margaret’s Center",
    "Neighborhood": "Lennox",
    "Address": "10217 Inglewood, Lennox",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-672-2208",
    "Hours of Operation": "M,W, F 9-12p, 1-4p",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "Serves residents in Inglewood, Lennox, Hawthorne, Lawndale, El Segundo, Manhattan Beach, Gardena, LA City in 90045, 90047 zip codes.Call first, same-day appt’s available",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "St. Andrew’s Presbyterian Church",
    "Neighborhood": "Redondo Beach",
    "Address": "301 Avenue D, Redondo Beach",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-540-5252",
    "Hours of Operation": "T & Th, 12-1pm ",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "First 100 guests in the serves Lawndale, Lennox, Inglewood, Westchester, El Segundo, parts of LA.   ",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Food Pantry LAX",
    "Neighborhood": "Inglewood",
    "Address": "355 E. Beach St, Inglewood",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-677-5597",
    "Hours of Operation": "T &Th, 10-noon",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "Can get emergency food once a week.",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Hope In Action",
    "Neighborhood": "Hermosa Beach",
    "Address": "2420 PCH, Hermosa Beach",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-374-4673",
    "Hours of Operation": "M & W 9a-12pm",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "Non-church members can get groceries once/month",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "St. Philomena Catholic Church",
    "Neighborhood": "Carson",
    "Address": "21900 S. Main St, Carson",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-835-7161",
    "Hours of Operation": "Tuesday 7:30-9:30A",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "Services Carson residents only",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Harbor Gateway/Torrance Outreach",
    "Neighborhood": "Torrance",
    "Address": "22400 S. Halldale, Ave, Torrance",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-328-3689",
    "Hours of Operation": "2nd and 4th Tuesday 9:30a",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "serves Torrance, Lomita, Gardena, Carson, Harbor G’Way",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "St. Margaret Mary Catholic Parish",
    "Neighborhood": "Lomita",
    "Address": "25511 Eshelman, Lomita",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-326-3364 x15",
    "Hours of Operation": "8:30-10:00A",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "serves Lomita, Wilmington, Harbor City, Torrance residents",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Calvary Light Christian Center",
    "Neighborhood": "Wilmington",
    "Address": "1101 N. Lakme Ave, Wilmington",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-830-3043",
    "Hours of Operation": "Wednesday 2-3:30P",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Crenshaw Baptist Church",
    "Neighborhood": "Torrance",
    "Address": "18749 Crenshaw Blvd, Torrance",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-323-2115",
    "Hours of Operation": "2nd Wednesday 8-10:30A",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "St. Paul’s United Methodist",
    "Neighborhood": "Redondo Beach",
    "Address": "2600 Nelson, Redondo Beach",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-370-4319",
    "Hours of Operation": "1st and 3rd Thurs 9-11A",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Calvary Assembly of God",
    "Neighborhood": "Lomita",
    "Address": "25501 Oak St, Lomita ",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-326-2757",
    "Hours of Operation": "2nd, 4th Thurs, 6-7p",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Oceangate Baptist",
    "Neighborhood": "Hawthorne",
    "Address": "13443 Oceangate Ave., Hawthorne",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-973-7031",
    "Hours of Operation": "Th 1-4p",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Salvation Army",
    "Neighborhood": "San Pedro",
    "Address": "138 S. Bandini St, San Pedro",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-832-7228",
    "Hours of Operation": "Th 9a-12p",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "Can receive groceries once a month",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Del Aire Baptist Church",
    "Neighborhood": "Hawthorne",
    "Address": "4951 W. 119th Pl, Hawthorne",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-676-8352",
    "Hours of Operation": "Fr 9a-1p",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Vermont Ave Baptist Church",
    "Neighborhood": "Torrance",
    "Address": "23325 S. Vermont Ave, Torrance",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-530-0533",
    "Hours of Operation": "3rd Sat 10-11a",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Rock Solid Christian Assembly",
    "Neighborhood": "San Pedro",
    "Address": "275 W. 1st St, San Pedro,",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-832-2788",
    "Hours of Operation": "2nd, 4th Sat 10:30-11:30a",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Warren Chapel CME Church",
    "Neighborhood": "San Pedro",
    "Address": "1039 W. Elberon Ave, San Pedro",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-547-5362",
    "Hours of Operation": "2nd, 4th Sat 1-3p",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Calvary Hawthorne Presbyterian Church",
    "Neighborhood": "Hawthorne",
    "Address": "13560 Hawthorne Blvd, Hawthorne,",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-676-1144",
    "Hours of Operation": "1st Sat 11:00a",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Hope Chapel",
    "Neighborhood": "Hawthorne",
    "Address": "13560 Hawthorne Blvd Hawthorne ",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-970-9023",
    "Hours of Operation": "3rd Sat. 12-12:30",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "First Christian Church of Wilmington",
    "Neighborhood": "Wilmington",
    "Address": "444 E. Lomita Blvd, Wilmington",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-835-4114",
    "Hours of Operation": "4th Sat 9-11:30a",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Holy Trinity Lutheran",
    "Neighborhood": "Inglewood",
    "Address": "9300 S. Crenshaw, Inglewood",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "323-757-1739",
    "Hours of Operation": "2nd, 4th Sat 1-2p",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "St. Lawrence Martyr Catholic Church",
    "Neighborhood": "Redondo Beach",
    "Address": "1900 S Prospect Ave., Redondo Bch",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-540-0329",
    "Hours of Operation": "1st Sat 8:30-10a",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "Numbers are drawn randomly at 7:55 am for food distribution rather than on a first come-first serve basis",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "St. Joseph Catholic Church",
    "Neighborhood": "Hawthorne",
    "Address": "11886 S. Acacia Ave, Hawthorne",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-679-1139",
    "Hours of Operation": "2nd Sun 8a-12:30p",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "House of Yahweh",
    "Neighborhood": "Lawndale",
    "Address": "4046 Marine Ave., Lawndale",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-675-1384",
    "Hours of Operation": "N/A",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "Apply for Food Outreach at office; if qualified, pick up food once/week from 2-3p; Emergency Food once/month call 310-675-1384 from 9-10a; first 10 callers",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 6 - Central LA",
    "Operator": "Compton College Food Pantry ",
    "Neighborhood": "Compton",
    "Address": " 1111 E Artesia Blvd, Compton, CA 90221",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-660-9000",
    "Hours of Operation": "N/A",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Free groceries ",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "God Provides Ministry ",
    "Neighborhood": "South El Monte",
    "Address": "2453 TROY AVE\r\rSOUTH EL MONTE, CA 91733",
    "Website": "http://www.godprovidesministry.org/",
    "Email": "N/A",
    "Phone": "626-442-4273",
    "Hours of Operation": "Mon-Fri\r 8AM to 4PM\r\r\rSat\r 8AM to 2PM",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "Call for eligibility requirements",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Grace Resources - Free Groceries",
    "Service Planning/Geographic Area": "SPA 1 - Antelope Valley",
    "Operator": "Grace Resources",
    "Neighborhood": "Lancaster",
    "Address": "Grace Resource Ctr. 45134 Sierra Hwy., Lancaster",
    "Website": "https://www.graceresources.org/",
    "Email": "N/A",
    "Phone": "(661) 940-5272",
    "Hours of Operation": "Tuesdays & Thursdays at 10:00 AM & 1:00 PM; Spanish only on Wednesdays at 10:00 AM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Lancaster Baptist - Groceries",
    "Service Planning/Geographic Area": "SPA 1 - Antelope Valley",
    "Operator": "Lancaster Baptist Church",
    "Neighborhood": "Lancaster",
    "Address": "First Baptist Church, 603 E. Lancaster Blvd, Lancaster",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "Saturday at 9:00 AM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "St. Bernard Church Food Pantry",
    "Neighborhood": "Belflower",
    "Address": "9627 Beach St., Bellflower, CA ",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-867-2337",
    "Hours of Operation": "Tuesday 10:00 AM - 1:00 PM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Salvation Army",
    "Neighborhood": "Belflower",
    "Address": "9644 Cedar St, Bellflower, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-804-0808",
    "Hours of Operation": "Tuesday 9:00 AM  - 12:00 PM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Bethany Church",
    "Neighborhood": "Belflower",
    "Address": "17054 Bixby Ave, Bellflower, CA ",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-866-1812",
    "Hours of Operation": "Tuesday 2:00 PM  - 3:00 PM, 4:00 PM - 5:00 PM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "The Lord's Church",
    "Neighborhood": "Belflower",
    "Address": "9740 Flower St, Bellflower, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-866-8283",
    "Hours of Operation": "2nd and 4th Wednesday 7:45 PM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Angel City Cafe",
    "Neighborhood": "Belflower",
    "Address": "16507 Bellflower Blvd, Bellflower, CA ",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-204-6461",
    "Hours of Operation": "2nd and 4th Wednesday 11:30 AM - 1:30 PM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Hosanna Chapel of Bellflower",
    "Neighborhood": "Belflower",
    "Address": "16517 S. Bellflower Blvd, Bellflower, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-925-5093",
    "Hours of Operation": "Wednesday-Thursday 8:30 PM - 9:00 PM ",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "Food is distributed after Bible Study 7:15PM"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "St. Dominic Savio Church, Bellflower, CA",
    "Neighborhood": "Belflower",
    "Address": "13400 Bellflower Blvd., Bellflower, CA ",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-920-7796",
    "Hours of Operation": "Thursday 8:00 AM - 10:00 AM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "Canned food, meat and bread"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Bellwood Baptist Church",
    "Neighborhood": "Belflower",
    "Address": "17614 Virginia Ave., Bellflower, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-925-4888",
    "Hours of Operation": "Thursday 10:00 AM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Cityline",
    "Neighborhood": "Belflower",
    "Address": "3936 Woodruff Ave., Bellflower, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-421-9374",
    "Hours of Operation": "4th Thursday 10:00 AM - 11:00 AM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "St. George's Church",
    "Neighborhood": "Belflower",
    "Address": "15721 Cornuta Ave., Bellflower, CA ",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-925-3706",
    "Hours of Operation": "2nd and 4th Tuesday 4:00PM - 6:00 PM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Holy Redeemer Lutheran",
    "Neighborhood": "Belflower",
    "Address": "14515 Blaine Ave., Bellflower, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-867-0714",
    "Hours of Operation": "Friday 9:00 AM - 10:30 AM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "Sign in at 8:00 AM"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Rosewood Church",
    "Neighborhood": "Belflower",
    "Address": "10115 Rose St., Bellflower, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-804-4778",
    "Hours of Operation": "Friday 3:00 PM - 4:00 PM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "The Journey @ Mayfair Church",
    "Neighborhood": "Lakewood",
    "Address": "6150 Bellflower Blvd, Lakewood, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-867-3198",
    "Hours of Operation": "1st Saturday 9:00 AM - 11:00AM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Lakewood First United Methodist",
    "Neighborhood": "Belflower",
    "Address": "4300 Bellflower Blvd., Bellflower, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-425-1219",
    "Hours of Operation": "2nd and 4th Saturday 9:00 AM - 11:00 AM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Hosanna Chapel of Bellflower",
    "Neighborhood": "Belflower",
    "Address": "16517 S Bellflower Blvd, Bellflower, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-925-5093",
    "Hours of Operation": "Sunday 11:45 AM - 12:30 PM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Bank",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Hawaiian Gardens Food Bank",
    "Neighborhood": "Hawaiian Gardens",
    "Address": "2212 Norwalk Blvd, Hawaiian Gardens, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-860-9097",
    "Hours of Operation": "Wednesdat 2:00 PM - 6:00 PM, thursday 9:30 AM - 3:30 PM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Calvary Chapel",
    "Neighborhood": "Downey",
    "Address": "12808 Woodruff Ave, Downey, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-803-5631",
    "Hours of Operation": "Mon, Wed, Fri 9:30AM 1:30PM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Ministry",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Calvary Chapel",
    "Neighborhood": "Downey",
    "Address": "12808 Woodruff Ave, Downey, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-803-5631",
    "Hours of Operation": "Tues 7:30PM - 8:30PM, Wed 4:00 PM - 7:00 PM, Sat 9:00 PM - 1:00 PM, Sun 9:30AM - 10:30AM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Bank",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Lawrence Ministries",
    "Neighborhood": "Hawaiian Gardens",
    "Address": "12441 E Farlow St, Hawaiian Gardens, CA ",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-653-9868",
    "Hours of Operation": "3rd Sat 10:00 AM - 2:00 PM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Cory's Kitchen - Irwindale Warehouse",
    "Neighborhood": "Irwindale",
    "Address": "1418 Arrow Hwy\r\rIrwindale, CA 91706",
    "Website": "https://www.coryskitchen.org/",
    "Email": "N/A",
    "Phone": "(626) 305-0392",
    "Hours of Operation": "Tuesdays 5:30PM to 7:30PM",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "Photo ID and two proofs of residence",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Cory's Kitchen - Baldwin Park New Beginnings",
    "Neighborhood": "Baldwin Park",
    "Address": "13020 Francisquito Ave\r\rBaldwin Park, CA 91706",
    "Website": "https://www.coryskitchen.org/",
    "Email": "N/A",
    "Phone": "626) 331-3322",
    "Hours of Operation": "Fridays 5:00PM to 7:00PM",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "Photo ID and two proofs of residence",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Inland Valley Hope Partners- Beta Program Center",
    "Neighborhood": "Paomona",
    "Address": "1095 W. Grand Ave.\r\rPomona, CA 91766 ",
    "Website": "http://www.inlandvalleyhopepartners.org/Program-Services/Food-Security-Program.asp",
    "Email": "N/A",
    "Phone": "909-622-3806, x#301 ",
    "Hours of Operation": "Monday – Thursday  9:00 a.m. – 3:00 p.m",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Inland Valley Hope Partners- San Dimas Center",
    "Neighborhood": "San Dimas",
    "Address": "110 E. Third Street San Dimas, CA 91773 ",
    "Website": "http://www.inlandvalleyhopepartners.org/Program-Services/Food-Security-Program.asp",
    "Email": "N/A",
    "Phone": "909-599-1103",
    "Hours of Operation": "Mon, Wed, Fri. 2:00 – 4:00 p.m.",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Inland Valley Hope Partners- Claremont Center",
    "Neighborhood": "Claremont",
    "Address": "660 N. Mountain Ave Claremont CA 91711",
    "Website": "http://www.inlandvalleyhopepartners.org/Program-Services/Food-Security-Program.asp",
    "Email": "N/A",
    "Phone": "909-622-3806, x#401",
    "Hours of Operation": "Tuesday & Thursday 12:30 - 4:30",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Inland Valley Hope Partners- Urban Mission Center",
    "Neighborhood": "Pomona",
    "Address": "810 South White  Pomona, CA 91768 ",
    "Website": "http://www.inlandvalleyhopepartners.org/Program-Services/Food-Security-Program.asp",
    "Email": "N/A",
    "Phone": "909-622-3806",
    "Hours of Operation": "Thursday 9:30 a.m. – 3:30 p.m",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Shepherd's Pantry",
    "Neighborhood": "Glendora",
    "Address": "657 E. Arrow Highway, Ste J\r\rGlendora, CA 91740 ",
    "Website": "https://www.shepherdspantry.com/services/",
    "Email": "N/A",
    "Phone": "(626) 852-7630",
    "Hours of Operation": "Wednesday & Thursday\r\r5:00PM to 7:00PM",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "San Gabriel Mission Food Pantry",
    "Neighborhood": "San Gabriel",
    "Address": "428 S. Mission Drive, San Gabriel, CA 91776",
    "Website": "https://parish.sangabrielmissionchurch.org/apps/events/2014/6/29/1647970/?id=1",
    "Email": "N/A",
    "Phone": "(626) 457-3035",
    "Hours of Operation": "Sunday\r\r8am – 10am",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Fountain of Love Church - Community Development\r\rCenter ",
    "Neighborhood": "Pomona",
    "Address": "188 W. Orange Grove Ave.\rPomona, CA ",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "Tuesday, Wednesday and\r\rThursday\r\r10:00 am to 2:00 pm \r",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 5 - West LA",
    "Operator": "Church on Pearl Pantry",
    "Neighborhood": "Santa Monica",
    "Address": "1520 Pearl Street, Santa Monica, CA 90405",
    "Website": "http://www.westsidefoodbankca.org/",
    "Email": "N/A",
    "Phone": "310-828-6016",
    "Hours of Operation": "Wednesday 2:30pm-5:30pm ",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 5 - West LA",
    "Operator": "Delaware Ave. SDA Pantry",
    "Neighborhood": "Santa Monica",
    "Address": "1845 20th Street, Santa Monica, CA 90404",
    "Website": "http://www.westsidefoodbankca.org/",
    "Email": "N/A",
    "Phone": "310-450-0919",
    "Hours of Operation": "Sunday 12:30pm-1:30pm",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 5 - West LA",
    "Operator": "St. Anne's Social Service",
    "Neighborhood": "Santa Monica",
    "Address": "2013 Colorado Ave, Santa Monica, CA 90404",
    "Website": "https://foodoasis.la/food-pantry/wsfb-st-annes-social-service/",
    "Email": "N/A",
    "Phone": "310-824-4411",
    "Hours of Operation": "Wednesday 4:00pm-5:30pm ",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 5 - West LA",
    "Operator": "St. Joseph Center",
    "Neighborhood": "Venice",
    "Address": "204 Hampton Drive, Los Angeles, CA 90401",
    "Website": "https://stjosephctr.org/education-vocation-training/",
    "Email": "N/A",
    "Phone": "310-396-6468 x313 ",
    "Hours of Operation": "Monday, Wednesday, Thursday 10:00am-12:00pm and Tuesday and Friday 1:00pm- 3:00pm",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution",
    "Service Planning/Geographic Area": "SPA 5 - West LA",
    "Operator": "Salvation Army, Santa Monica",
    "Neighborhood": "Santa Monica",
    "Address": "1533 4th Street, Santa Monica, CA 90401",
    "Website": "http://www.westsidefoodbankca.org/index.php?option=com_content&task=view&id=70&Itemid=94",
    "Email": "N/A",
    "Phone": "310-451-1358",
    "Hours of Operation": "Monday thru Friday 9:00am - 11:00am ",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
},
{
    "Updated by SPA Leadership": "N/A",
    "Program Name": "Food Distribution ",
    "Service Planning/Geographic Area": "SPA 5 - West LA",
    "Operator": "SOVA West ",
    "Neighborhood": "Pico-Robertson",
    "Address": "8846 W. Pico Blvd, Los Angeles, CA 90035 ",
    "Website": "https://www.jfsla.org/sslpage.aspx?pid=300",
    "Email": "N/A",
    "Phone": "310-288-0286 (when pantry is open) 818-988-7682",
    "Hours of Operation": "Sunday 9:00am-12:00pm (open every Sunday except holiday weekends) Monday thru Thursday 10:00am- 1:30pm ",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Population Notes (Note if only a specific population is served) ": "N/A",
    "Notes": "N/A"
}
]
]