const laundry = [
  [
    {
      PROGRAM_NAME: "Aroma Laundry & Water",
      SERVICE_PLANNING_AREA: "SPA 4 - Metro LA",
      OPERATOR: "Aroma Laundry & Water",
      NEIGHBORHOOD: "Echo Park",
      ADDRESS: "1448 N Alvarado St, Los Angeles ",
      PHONE: "(323) 400-8534 ",
      HOURS_OF_OPERATION: "3rd Tuesday of every Month: 6:00pm-8:00pm",
      WALK_INS: "Yes",
    },
    {
      PROGRAM_NAME: "Lavanderia",
      SERVICE_PLANNING_AREA: "SPA 4 - Metro LA",
      OPERATOR: "Lavanderia",
      NEIGHBORHOOD: "Lincoln Heights",
      ADDRESS: "3031 N. Broadway Lincoln Heights, Los Angeles, ",
      PHONE: "(626) 731-5502",
      HOURS_OF_OPERATION: "Last Tuesday of every Month: 6:00pm-8:30pm",
      WALK_INS: "Yes",
    },
    {
      PROGRAM_NAME: "Los Lavanderos Coin Laundry",
      SERVICE_PLANNING_AREA: "SPA 4 - Metro LA",
      OPERATOR: "Los Lavanderos Coin Laundry",
      NEIGHBORHOOD: "East Hollywood",
      ADDRESS: "4371 Melrose Ave, Los Angeles, ",
      PHONE: "(865) 776-6234",
      HOURS_OF_OPERATION: "Last Wednesday of every Month: 7:00pm-9:00pm",
      WALK_INS: "Yes",
    },
    {
      PROGRAM_NAME: "Lavanderia Coin Laundry",
      SERVICE_PLANNING_AREA: "SPA 4 - Metro LA",
      OPERATOR: "Lavanderia Coin Laundry",
      NEIGHBORHOOD: "Highland Park",
      ADDRESS: "5538 York Blvd, Los Angeles",
      PHONE: "(818) 322-9078",
      HOURS_OF_OPERATION: "Last Sunday of every Month: 1:00pm-2:00pm",
      WALK_INS: "Yes",
    },
    {
      PROGRAM_NAME: "Wash & Dry",
      SERVICE_PLANNING_AREA: "SPA 4 - Metro LA",
      OPERATOR: "Wash & Dry",
      NEIGHBORHOOD: "Highland Park",
      ADDRESS: "6400 York Blvd Los Angeles",
      PHONE: "(818) 322-9078",
      HOURS_OF_OPERATION: "Last Sunday of every Month: 1:00pm-2:00pm",
      WALK_INS: "Yes",
    },
    {
      PROGRAM_NAME: "Laundry Love",
      SERVICE_PLANNING: "SPA 5 - West LA",
      OPERATOR: "Gary's Cleaners & Coin Laundry",
      NEIGHBORHOOD: "Culver City",
      ADDRESS: "12701 Washington Place, Los Angeles, CA 90066",
      "Website": "https://laundrylove.org/locations/",
      PHONE: "(310) 306-8222",
      HOURS_OF_OPERATION: "3rd Sunday of every Month & 4th Sunday in June: 5:00pm-7:00pm",
      WALK_INS: "Yes",
    },
    {
      PROGRAM_NAME: "Laundry Love",
      SERVICE_PLANNING: "SPA 8 - South Bay",
      OPERATOR: "Clean Scene LAundry",
      NEIGHBORHOOD: "Redondo Beach",
      ADDRESS: "2301 Artesia Blvd, Redondo Beach, ",
      PHONE: "(310) 376-8989 ",
      HOURS_OF_OPERATION: "Last Wednesday of every Month: 7:00pm-10:00pm (last load at 8:45pm",
      WALK_INS: "Yes",
    },
    {
      PROGRAM_NAME: "Laundry Love",
      SERVICE_PLANNING: "SPA 8 - South Bay",
      OPERATOR: "King's Laundry",
      NEIGHBORHOOD: "Harbor City",
      ADDRESS: "1330 PCH, Harbor City, ",
      PHONE: "(310) 508-9214 ",
      HOURS_OF_OPERATION: "4th Thursday of every Month: 4:00pm-6:30pm",
      WALK_INS: "Yes",
    },
    {
      PROGRAM_NAME: "Laundry Love",
      SERVICE_PLANNING: "SPA 8 - South Bay",
      OPERATOR: "Coin Laundromat",
      NEIGHBORHOOD: "San Pedro",
      ADDRESS: "1000 W. Bandini St, San Pedro, ",
      PHONE: "(310) 901-5490 ",
      HOURS_OF_OPERATION: "1st and 3rd Wednesdays of every Month: 6:00pm-8:00pm",
      WALK_INS: "Yes",
    },
    {
      PROGRAM_NAME: "Laundry Love",
      SERVICE_PLANNING: "SPA 8 - South Bay",
      OPERATOR: "Lucy's Fluff &Fold",
      NEIGHBORHOOD: "San Pedro",
      ADDRESS: "112 S. Pacific Ave, San Pedro, ",
      PHONE: "(310) 901-5490",
      HOURS_OF_OPERATION: "2nd and 4th Wednesday of every Month: 6:00pm-8:30pm",
      WALK_INS: "Yes",
    },
    {
      PROGRAM_NAME: "Laundry Love",
      SERVICE_PLANNING: "SPA 8 - South Bay",
      OPERATOR: "La Familia Coin LAundry",
      NEIGHBORHOOD: "Lomita",
      ADDRESS: "1739 Lomita Blvd, Lomita ",
      PHONE: "N/A",
      HOURS_OF_OPERATION: "1st Saturdays of every Month: 1:00pm-4:00pm and last signup at 3:30pm | 2nd Saturdays of every Month: 12:00pm-3:00pm and 4 loads of laundry per person.",
      WALK_INS: "Yes",
    },
    {
      PROGRAM_NAME: "Laundry Love",
      SERVICE_PLANNING: "SPA 8 - South Bay",
      OPERATOR: "Soap City Laundromat",
      NEIGHBORHOOD: "Wilmington",
      ADDRESS: "208 W. Anaheim St. Suite A, Wilmington",
      PHONE: "N/A",
      HOURS_OF_OPERATION: "4th Thursday of every Month: 5:30pm-7:30pm",
      WALK_INS: "Yes",
    },
    {
      PROGRAM_NAME: "Mental Health America -AVES",
      SERVICE_PLANNING: "SPA 1 - Antelope Valley",
      OPERATOR: "Mental Health America",
      NEIGHBORHOOD: "Lancaster",
      ADDRESS: "506 W Jackman St, Lancaster, CA 93534",
      "Website": "https://www.mhalaaves.org/programs_services.php",
      PHONE: "N/A",
      HOURS_OF_OPERATION: "Monday-Friday: 8:00am-5:30pm",
      WALK_INS: "Yes",
    },
    {
      PROGRAM_NAME: "Laundry Love",
      SERVICE_PLANNING: "SPA 3 - San Gabriel Valley",
      OPERATOR: "Lucy's Laundrymart",
      NEIGHBORHOOD: "Pomona",
      ADDRESS: "365 W. Holt Ave, Pomona CA 91768",
      PHONE: "(909) 833-1283",
      HOURS_OF_OPERATION: "3rd Wednesday of every Month: 6:00pm-8:00pm",
      WALK_INS: "N/A",
    },
    {
      PROGRAM_NAME: "Laundry Love",
      SERVICE_PLANNING: "SPA 6 - Central LA",
      OPERATOR: "Launderland West Adams",
      NEIGHBORHOOD: "Culver City",
      ADDRESS: "5238 W Adams blvd Los Angeles Ca 90016",
      PHONE: "(310) 592-1839",
      HOURS_OF_OPERATION: "1st Wednesday of every Month: Time is N/A",
      WALK_INS: "Yes",
    }
  ]
]