// object model for each resource
{
    programName: "",
    spa: "",
    operator: "",
    city: "",
    address: "",
    website: "",
    phone: "",
    hours: "",
    walkIn: boolean,
    eligibility: ""
}

const laundry = [
[
{
    "Updated by SPA Leadership ": "",
    "Program Name": "Aroma Laundry & Water",
    "Service Planning/Geographic Area": "SPA 4 - Metro LA",
    "Operator": "Aroma Laundry & Water",
    "Neighborhood": "Echo Park",
    "Address": "1448 N Alvarado St, Los Angeles ",
    "Website": "",
    "Email": "",
    "Phone": "(323) 400-8534 ",
    "Hours of Operation": "6:00pm - 8:00pm 3rd Tuesday of every month",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": ""
},
{
    "Updated by SPA Leadership ": "",
    "Program Name": "Lavanderia",
    "Service Planning/Geographic Area": "SPA 4 - Metro LA",
    "Operator": "Lavanderia",
    "Neighborhood": "Lincoln Heights",
    "Address": "3031 N. Broadway Lincoln Heights, Los Angeles, ",
    "Website": "",
    "Email": "",
    "Phone": "626-731-5502",
    "Hours of Operation": "6:00pm - 8:30pm Last Tuesday of the month  ",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": ""
},
{
    "Updated by SPA Leadership ": "",
    "Program Name": "Los Lavanderos Coin Laundry",
    "Service Planning/Geographic Area": "SPA 4 - Metro LA",
    "Operator": "Los Lavanderos Coin Laundry",
    "Neighborhood": "East Hollywood",
    "Address": "4371 Melrose Ave, Los Angeles, ",
    "Website": "",
    "Email": "",
    "Phone": "865-776-6234",
    "Hours of Operation": "7:00pm - 9:00pm Last Wednesday of the month ",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": ""
},
{
    "Updated by SPA Leadership ": "",
    "Program Name": "Lavanderia Coin Laundry",
    "Service Planning/Geographic Area": "SPA 4 - Metro LA",
    "Operator": "Lavanderia Coin Laundry",
    "Neighborhood": "Highland Park",
    "Address": "5538 York Blvd, Los Angeles",
    "Website": "",
    "Email": "",
    "Phone": "818-322-9078",
    "Hours of Operation": "1:00pm - 2:00pm (Last Sunday of the month ",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": ""
},
{
    "Updated by SPA Leadership ": "",
    "Program Name": "Wash & Dry",
    "Service Planning/Geographic Area": "SPA 4 - Metro LA",
    "Operator": "Wash & Dry",
    "Neighborhood": "Highland Park",
    "Address": "6400 York Blvd Los Angeles",
    "Website": "",
    "Email": "",
    "Phone": "818-322-9078",
    "Hours of Operation": "1:00PM - 2:00PM (last Sunday of the month  ",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": ""
},
{
    "Updated by SPA Leadership ": "",
    "Program Name": "Laundry Love",
    "Service Planning/Geographic Area": "SPA 5 - West LA",
    "Operator": "Gary's Cleaners & Coin Laundry",
    "Neighborhood": "Culver City",
    "Address": "12701 Washington Place, Los Angeles, CA 90066",
    "Website": "https://laundrylove.org/locations/",
    "Email": "",
    "Phone": "310-306-8222",
    "Hours of Operation": "5:00PM- 7:00PM (3rd Sunday of the month- 4th Sunday in June)",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": ""
},
{
    "Updated by SPA Leadership ": "",
    "Program Name": "Laundry Love",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Clean Scene LAundry",
    "Neighborhood": "Redondo Beach",
    "Address": "2301 Artesia Blvd, Redondo Beach, ",
    "Website": "",
    "Email": "",
    "Phone": " 310-376-8989 ",
    "Hours of Operation": "Last Wednesday, 7:00-10:00 pm (last load 8:45 pm) ",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": ""
},
{
    "Updated by SPA Leadership ": "",
    "Program Name": "Laundry Love",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "King's Laundry",
    "Neighborhood": "Harbor City",
    "Address": "1330 PCH, Harbor City, ",
    "Website": "",
    "Email": "",
    "Phone": " 310-508-9214 ",
    "Hours of Operation": "4th Thursday, doors open at 4:00 pm, last wash 6:30 pm ",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": ""
},
{
    "Updated by SPA Leadership ": "",
    "Program Name": "Laundry Love",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Coin Laundromat",
    "Neighborhood": "San Pedro",
    "Address": "1000 W. Bandini St, San Pedro, ",
    "Website": "",
    "Email": "",
    "Phone": "310-901-5490 ",
    "Hours of Operation": "1st & 3rd Wednesdays, 6:00-8:00 pm ",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": ""
},
{
    "Updated by SPA Leadership ": "",
    "Program Name": "Laundry Love",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Lucy's Fluff &Fold",
    "Neighborhood": "San Pedro",
    "Address": "112 S. Pacific Ave, San Pedro, ",
    "Website": "",
    "Email": "",
    "Phone": "310-901-5490",
    "Hours of Operation": "2nd & 4th Wednesday, 6:00-8:30 pm ",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": ""
},
{
    "Updated by SPA Leadership ": "",
    "Program Name": "Laundry Love",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "La Familia Coin LAundry",
    "Neighborhood": "Lomita",
    "Address": "1739 Lomita Blvd, Lomita ",
    "Website": "",
    "Email": "",
    "Phone": "",
    "Hours of Operation": "1st Saturdays, 1:00-4:00  pm, signups end 3:30 pm 2nd Saturdays, 12:00-3:00 pm 4 loads of laundry/person",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": ""
},
{
    "Updated by SPA Leadership ": "",
    "Program Name": "Laundry Love",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Soap City Laundromat",
    "Neighborhood": "Wilmington",
    "Address": "208 W. Anaheim St. Suite A, Wilmington",
    "Website": "",
    "Email": "",
    "Phone": "",
    "Hours of Operation": "4th Thursday, 5:30pm signups end 7:30pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": ""
},
{
    "Updated by SPA Leadership ": "",
    "Program Name": "Mental Health America -AVES",
    "Service Planning/Geographic Area": "SPA 1 - Antelope Valley",
    "Operator": "Mental Health America",
    "Neighborhood": "Lancaster",
    "Address": "506 W Jackman St, Lancaster, CA 93534",
    "Website": "https://www.mhalaaves.org/programs_services.php",
    "Email": "",
    "Phone": "",
    "Hours of Operation": "8:00 AM - 5:30 PM Weekdays",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": ""
},
{
    "Updated by SPA Leadership ": "",
    "Program Name": "Laundry Love",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Lucy's Laundrymart",
    "Neighborhood": "Pomona",
    "Address": "365 W. Holt Ave, Pomona CA 91768",
    "Website": "",
    "Email": "",
    "Phone": "909-833-1283",
    "Hours of Operation": "6:00pm -8:00pm 3rd Wed of the month",
    "Walk-Ins Allowed?": "",
    "Eligibility Requirements": ""
},
{
    "Updated by SPA Leadership ": "",
    "Program Name": "Laundry Love",
    "Service Planning/Geographic Area": "SPA 6 - Central LA",
    "Operator": "Launderland West Adams",
    "Neighborhood": "Culver City",
    "Address": "5238 W Adams blvd Los Angeles Ca 90016",
    "Website": "",
    "Email": "",
    "Phone": 3105921839,
    "Hours of Operation": "1st Wed of the month",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": ""
}
]
]