const meals = [
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Church in the Park- Breakfast",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "First Church of the Nazarene of Pasadena",
    "Neighborhood": "Pasadena",
    "Address": "275 S Raymond Ave, Pasadena, CA 91105",
    "Website": "https://www.paznaz.org/compassionate-ministries/",
    "Email": "info@paznaz.org",
    "Phone": "N/A",
    "Hours of Operation": "Sun. 8:45am",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "On corner of Del Mar & Fair Oaks. Sign up tp "
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Free Dinner",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Pasadena Church",
    "Neighborhood": "Pasadena",
    "Address": "404 E. Washington Blvd Pasadena, CA  91104",
    "Website": "https://www.pasadenachurch.com/home",
    "Email": "N/A",
    "Phone": "(626) 794-2951",
    "Hours of Operation": "Mon, Wed, & Fri 6-7pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Free breakfast and lunch",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Union Station Homeless Services",
    "Neighborhood": "Pasadena",
    "Address": "412 S Raymond Ave Pasadena, CA 91105",
    "Website": "https://unionstationhs.org/",
    "Email": "info@unionstationhs.org ",
    "Phone": "(626) 240-4550",
    "Hours of Operation": "Free breakfast 9:00 am & 9:30 am and lunch 12 pm & 12:30pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Christian Food Center",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "N/A",
    "Neighborhood": "Fashion District",
    "Address": "1101 E Washington Blvd LA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "800-798-7099",
    "Hours of Operation": "N/A",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Downtown Womens Center",
    "Service Planning/Geographic Area": "SPA 4 - Metro LA",
    "Operator": "Downtown Womens Center",
    "Neighborhood": "Downtown Los Angeles",
    "Address": "442 S San Pedro St Los Angeles, CA 90011",
    "Website": "https://www.downtownwomenscenter.org",
    "Email": "N/A",
    "Phone": "213-680-0600",
    "Hours of Operation": "Breakfast 8:00 am & 9:00 am and lunch 12 pm & 1:00pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Good Shephard (Women Only)",
    "Service Planning/Geographic Area": "SPA 4 - Metro LA",
    "Operator": "N/A",
    "Neighborhood": "Historic Filipenotown",
    "Address": "267 Belmont Ave Los Angeles, CA 90026",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "213-250-5251",
    "Hours of Operation": "N/A",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Silverlake Church",
    "Service Planning/Geographic Area": "SPA 4 - Metro LA",
    "Operator": "Silverlake Church",
    "Neighborhood": "Silverlake",
    "Address": "2930 Hyperion Ave Los Angeles, CA 90027",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "323-663-3151",
    "Hours of Operation": "N/A",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Hollywood Pres Children Center",
    "Service Planning/Geographic Area": "SPA 4 - Metro LA",
    "Operator": "Hippie Kitchen",
    "Neighborhood": "Hollywood",
    "Address": "1760 N Gower St, Los Angeles, CA 90028",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "323-463-7161",
    "Hours of Operation": "N/A",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Hippie Kitchen",
    "Service Planning/Geographic Area": "SPA 4 - Metro LA",
    "Operator": "N/A",
    "Neighborhood": "Downtown Los Angeles",
    "Address": "821 E 6th St, Los Angeles, CA 90021",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "213-614-9615",
    "Hours of Operation": "N/A",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "St Francis Center",
    "Service Planning/Geographic Area": "SPA 4 - Metro LA",
    "Operator": "St Francis Church ",
    "Neighborhood": "University Park",
    "Address": "1835 S Hope St, Los Angeles, CA 90015",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "213-747-5347",
    "Hours of Operation": "N/A",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Bread & Roses Cafe",
    "Service Planning/Geographic Area": "SPA 4 - Metro LA",
    "Operator": "St. Joseph Center's Homeless Service Center",
    "Neighborhood": "Venice",
    "Address": "663 Rose Ave Los Angeles, CA 90291",
    "Website": "https://stjosephctr.org/program/outreach-engagement/",
    "Email": "N/A",
    "Phone": "310-399-6878",
    "Hours of Operation": "Mon, Tue, Thur: 7:30am-4:30pm Wed: 7:30am-12:00pm and Fri: 7:30am-3:30pm",
    "Walk-Ins Allowed?": "No",
    "Eligibility Requirements": "Hot meals by appointment Monday-Friday must make reservation at Homeless Service Center",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Grace Lutheran Church",
    "Service Planning/Geographic Area": "SPA 5 - West LA",
    "Operator": "Grace Lutheran Church",
    "Neighborhood": "Culver City",
    "Address": "4427 Overland Ave Culver City, CA 90230",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-559-1027",
    "Hours of Operation": "Mon: 4:30pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "The People Concern",
    "Service Planning/Geographic Area": "SPA 5 - West LA",
    "Operator": "The People Concern",
    "Neighborhood": "Santa Monica",
    "Address": "503 Olympic Blvd Santa Monica, CA 90401",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-450-4050",
    "Hours of Operation": "Mon-Fri: 9:00am-12:00pm & 3:30pm-4:00pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Safe Place for Youth (Youth Only)",
    "Service Planning/Geographic Area": "SPA 5 - West LA",
    "Operator": "Safe Place for Youth",
    "Neighborhood": "Venice",
    "Address": "2469 Lincoln Blvd Los Angeles, CA 90291",
    "Website": "http://www.safeplaceforyouth.org/drop_in",
    "Email": "N/A",
    "Phone": "310-902-2283",
    "Hours of Operation": "Tue, Wed and & Thur: 1:00pm-5:00pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "Ages 16-25 Only",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Catholic Charities",
    "Service Planning/Geographic Area": "SPA 5 - West LA",
    "Operator": "Catholic Charities",
    "Neighborhood": "Venice",
    "Address": "211 3rd Ave, Los Angeles, CA 90291",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-392-8701",
    "Hours of Operation": "Mon-Fri: 8:30am-5:00pm Sat and Sun: 9:00am-2:00pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "SSG HOPICS",
    "Service Planning/Geographic Area": "SPA 5 - West LA",
    "Operator": "SSG HOPICS",
    "Neighborhood": "South Los Angeles",
    "Address": "5849 CrockerSt Los Angeles, CA 90003",
    "Website": "https://www.hopics.org/",
    "Email": "N/A",
    "Phone": "323-432-4399",
    "Hours of Operation": "N/A",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Watts Labor Community Action Commitee ",
    "Service Planning/Geographic Area": "SPA 6 - Central LA",
    "Operator": "Watts Labor Community Action Committee",
    "Neighborhood": "Hacienda Village",
    "Address": "958 E 108th Street Los Angeles, CA ",
    "Website": "http://www.wlcac.org/",
    "Email": "N/A",
    "Phone": "323-563-4721",
    "Hours of Operation": "N/A",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "St. Lawrence Martyr Catholic Church ",
    "Service Planning/Geographic Area": "SPA 6 - Central LA",
    "Operator": "St. Lawrence Martyr Catholic Church ",
    "Neighborhood": "Redondo Beach",
    "Address": "1900 S Prospect Ave., Redondo Bch",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-540-0329 ",
    "Hours of Operation": "Mon-Thur: 8:30am- 3:30pm, Fri-Sun: 8:30am- 1pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Beacon Light Mission ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Beacon Light Mission ",
    "Neighborhood": "Wilmington",
    "Address": "525 Broad St, Wilmington, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": " 310-830-7063 ",
    "Hours of Operation": "Mon-Sun: 5:45 pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "Must attend chapel first",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "St. Catherine Laboure Catholic Church ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "St. Catherine Laboure Catholic Church ",
    "Neighborhood": "Torrance",
    "Address": "3846 Redondo Bch Blvd, Torrance, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-323-8900 ",
    "Hours of Operation": "Mon- Fri: 11am-1pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Calvary Hawthorne Presbyterian Church ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Calvary Hawthorne Presbyterian Church ",
    "Neighborhood": "Hawthorne",
    "Address": "13560 Hawthorne Blvd, Hawthorne, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-676-1144",
    "Hours of Operation": "Thur, fri: 11a-2pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Salvation Army",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Salvation Army",
    "Neighborhood": "Inglewood",
    "Address": "324 E. Queen St, Inglewood, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-677-3375",
    "Hours of Operation": "Mon- Fri: 11am",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "first 40 ",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "St. James Catholic Church",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "St. James Catholic Church",
    "Neighborhood": "Redondo Beach",
    "Address": "415 Vincent, Redondo Beach, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": " 310-530-2756 ",
    "Hours of Operation": "Mon, Wed, & Fri: 1pm -2 pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "St. Margaret’s Center",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "St. Margaret’s Center",
    "Neighborhood": "Lennox",
    "Address": "10217 Inglewood, Lennox, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-672-2208 ",
    "Hours of Operation": "Mon, Wed, & Fri: 8:30am-5pm (closed daily 12pm-1pm)",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "St. John Evangelical Lutheran Church ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "St. John Evangelical Lutheran Church ",
    "Neighborhood": "Gardena",
    "Address": "14517 Crenshaw Blvd, Gardena, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-676-8804 ",
    "Hours of Operation": "mon & Fri: 6pm, Sun 12pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Curt’s Kitchen ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Curt’s Kitchen ",
    "Neighborhood": "San Pedro",
    "Address": "129 North Pacific Ave. San Pedro, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-831-3480 ",
    "Hours of Operation": "Mon & Tue: 5:30pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "St. Andrew’s Presbyterian Church ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "St. Andrew’s Presbyterian Church ",
    "Neighborhood": "Redondo Beach",
    "Address": "301 Avenue D, Redondo Beach, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": " 310-540-5252 ",
    "Hours of Operation": "Tue & Thur: 12pm- 1pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Homeless Resources Fair & Mobile Shower ",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "More Than Just A Meal ",
    "Neighborhood": "South El Monte",
    "Address": "\r\r1201 Loma Ave (Area A, Building 21)\r\rSouth El Monte, California 91733",
    "Website": "https://www.facebook.com/morethansjustamealinc/?__tn__=%2Cd%2CP-R&eid=ARCehk-NheP5NPHIdPPpC62rvOfPFuTPb4ZJjW4XzKU77zgDoPCMqncElzVZnjC1RXbVgYgIgrM5qwo9",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "11:00am - 3:00pm  Every Thursday ",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "St. Paul’s United Methodist (Proj. Needs) ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "St. Paul’s United Methodist (Proj. Needs) ",
    "Neighborhood": "Redondo Beach",
    "Address": "2600 Nelson, Redondo Beach, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-370-4319 ",
    "Hours of Operation": "Tues. 6-7pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Calvary Light Christian Center ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Calvary Light Christian Center ",
    "Neighborhood": "Wilmington",
    "Address": "1101 N. Lakme Ave, Wilmington, ",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": " 310-830-3043 ",
    "Hours of Operation": "Wed. 12pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "First United Methodist Church (Shared Bread) ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "First United Methodist Church (Shared Bread) ",
    "Neighborhood": "Redondo Beach",
    "Address": "243 S. Broadway, Redondo Bch, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": " 310-372-8445 ",
    "Hours of Operation": "Wed. 5-7pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "First Baptist Church ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "First Baptist Church ",
    "Neighborhood": "San Pedro",
    "Address": "555 W. 7th St, San Pedro, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": " 310-548-1333 ",
    "Hours of Operation": "Thur. 6pm, Sun 8am",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Journey South Bay Community Church ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Journey South Bay Community Church ",
    "Neighborhood": "Redondo Beach",
    "Address": "2761 190th St., Redondo Beach, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-371-0411 ",
    "Hours of Operation": "Thur. 6pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Torrance First Baptist Church ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Torrance First Baptist Church ",
    "Neighborhood": "Torrance",
    "Address": "2118 W. Carson, Torrance, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-328-5030 ",
    "Hours of Operation": "first Sat. 11am-1pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Walteria United Methodist Church",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Walteria United Methodist Church",
    "Neighborhood": "Torrance",
    "Address": "3646 Newton St., Torrance, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-375-0622 ",
    "Hours of Operation": "Second Sat. 11am-1pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "St. Andrew’s Episcopal Church ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "St. Andrew’s Episcopal Church ",
    "Neighborhood": "Torrance",
    "Address": "1432 Engracia, Torrance, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-328-3781",
    "Hours of Operation": "Third Sat. 11am-1pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "First United Methodist Church",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "First United Methodist Church",
    "Neighborhood": "Torrance",
    "Address": "1551 El Prado, Torrance, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-328-3242 ",
    "Hours of Operation": "Fourth Sat. 11am-1pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Riviera United Methodist Church ",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Riviera United Methodist Church ",
    "Neighborhood": "Redondo Beach",
    "Address": "375 Palos Verdes Blvd., Redondo Bch, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": " 310-378-9273 ",
    "Hours of Operation": "fifth Sat. 11am-1pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Meal",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Bethany Church",
    "Neighborhood": "Bellflower",
    "Address": "17054 Bixby Ave, Bellflower, CA ",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-866-1812",
    "Hours of Operation": "Wednesday 4:15 PM - 5:15 PM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Breakfast and Lunch",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Journey of Faith",
    "Neighborhood": "Bellflower",
    "Address": "17456 Downey Ave., Bellflower, CA ",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-634-2910",
    "Hours of Operation": "Saturday 9:30 AM - 12:00 PM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Breakfast",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Calvary Baptist Church",
    "Neighborhood": "Bellflower",
    "Address": "14722 Clark Ave., Bellflower, CA ",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-925-3706",
    "Hours of Operation": "Saturday 8:00 AM - 9:00 AM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Meals",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Life Center Church",
    "Neighborhood": "Lakewood",
    "Address": "6022 Candlewood St, Lakewood, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-866-9078",
    "Hours of Operation": "3rd Saturday of the month",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Meals",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "SSS Good Samaritan Association",
    "Neighborhood": "Lakewood",
    "Address": "5035 Hedda St, Lakewood, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-619-0467",
    "Hours of Operation": "4th Saturday, 8:00 AM - 10:00 AM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Meals",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Cerritos Crossroads Multinational Church",
    "Neighborhood": "Cerritos",
    "Address": "12229 Del Amo Blvd, Cerritos, CA 90703",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-809-4143",
    "Hours of Operation": "Friday 8:30 AM - 9:30PM. Sunday 8:45 PM - 9:30 PM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Meals",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "St. Paul on the Cross Catholic Church",
    "Neighborhood": "La Mirada",
    "Address": "14020 Foster Rd, La Mirada, CA 90638",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "(562) 921-2914",
    "Hours of Operation": "Tuesdays 9:30 AM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Meals",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Saint Matthias Church Soup Kitchen",
    "Neighborhood": "Wittier",
    "Address": "7056 Washington Ave, Whittier, CA 90602",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-698-4347",
    "Hours of Operation": "M-F 3PM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Meals",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Parroquia Sargrada Church",
    "Neighborhood": "Huntington Park",
    "Address": "6401 Rugby Ave, Huntington Park, CA ",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "M-F 9AM-2PM",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Meals and clothing ",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Purpose Church",
    "Neighborhood": "Pomona",
    "Address": "586 N. Main St. \r\rPomona, CA 91768",
    "Website": "https://purposechurch.com/localimpact/",
    "Email": "N/A",
    "Phone": "(909) 629-5277 x3014",
    "Hours of Operation": "3rd Saturday ",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Helping Hands Caring\r\rHearts Ministry ",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "New Harvest Church \r",
    "Neighborhood": "Pomona",
    "Address": "480 W. Monterey St.\r\rPomona, Ca.",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "Sunday Dinner @ 3:45\r\rPantry 3:30-5:30 \r",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A",
    "Notes": "N/A"
},
{
    "Updated By SPA Leadership ": "N/A",
    "Program Name": "Meals for those in Motels",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Inter City Volunteers ",
    "Neighborhood": "Pomona",
    "Address": "P.O. Box 209\r\rPomona, CA 91769",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "909-865-8853 ",
    "Hours of Operation": "Tuesday to Friday\r\r9:00 am to 5:30 pm",
    "Walk-Ins Allowed?": "No",
    "Eligibility Requirements": "Provides hot meals to\r\rhomeless individuals and families living in\r\rmotels",
    "Notes": "N/A"
}
]
