<<<<<<< HEAD
=======
// object model for each resource
{
    programName: "N/A",
    spa: "N/A",
    operator: "N/A",
    city: "N/A",
    address: "N/A",
    website: "N/A",
    phone: "N/A",
    hours: "N/A",
    walkIn: boolean,
    eligibility: "N/A"
}

>>>>>>> master
const shower = [
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "Showers",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Union Station Homeless Services",
    "Neighborhood": "Pasadena",
    "Address": "412 S Raymond Ave Pasadena, CA 91105",
    "Website": "https://unionstationhs.org/",
    "Email": "info@unionstationhs.org ",
    "Phone": "(626) 240-4550",
    "Hours of Operation": "showers available daily, sign-up at 7am",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A"
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "Hollywood Adventist Church",
    "Service Planning/Geographic Area": "SPA 4 - Metro LA",
    "Operator": "Shower of Hope",
    "Neighborhood": "Hollywood",
    "Address": "1711 N Van Ness Ave, Hollywood 90028",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "Tuesdays 10am – 3pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A"
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "Hollywood 1st Baptist Church ",
    "Service Planning/Geographic Area": "SPA 4 - Metro LA",
    "Operator": "Shower of Hope",
    "Neighborhood": "Hollywood",
    "Address": "6682 Selma Ave Hollywood ",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "Fridays 2pm – 5pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A"
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "Lincoln Heights ",
    "Service Planning/Geographic Area": "SPA 4 - Metro LA",
    "Operator": "Shower of Hope",
    "Neighborhood": "Montecito Heights",
    "Address": "3501 Valley Blvd Los Angeles",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "Thursdays 9am – 1pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A"
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "Cypress Park",
    "Service Planning/Geographic Area": "SPA 4 - Metro LA",
    "Operator": "Shower of Hope",
    "Neighborhood": "Downtown Los Angeles",
    "Address": "4212 Poplar St Los Angeles",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "Thursdays 9am – 1pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A"
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "Boyle Heights (Clinica Romero)",
    "Service Planning/Geographic Area": "SPA 4 - Metro LA",
    "Operator": "Shower of Hope",
    "Neighborhood": "Rampart Village",
    "Address": "123 S Alvarado St Los Angeles",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "Fridays 9am – 12pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A"
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "MacArthur Park",
    "Service Planning/Geographic Area": "SPA 4 - Metro LA",
    "Operator": "Shower of Hope",
    "Neighborhood": "Westlake",
    "Address": "2230 W 6th St Los Angeles",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "Fridays 9am – 1pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A"
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "Highland Park All Saints Church",
    "Service Planning/Geographic Area": "SPA 4 - Metro LA",
    "Operator": "Shower of Hope",
    "Neighborhood": "Highland Park",
    "Address": "5619 Monte Vista St Los Angeles",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "Saturdays 9am – 1pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A"
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "Safe Place for Youth ",
    "Service Planning/Geographic Area": "SPA 5 - West LA",
    "Operator": "Safe Place for Youth",
    "Neighborhood": "Venice",
    "Address": "2469 Lincoln Blvd Los Angeles, CA 90291",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "310-902-2283",
    "Hours of Operation": "Tue, Wed and & Thur: 1:00pm-5:00pm",
    "Walk-Ins Allowed?": "No",
    "Eligibility Requirements": "Walk-Ins welcome Tue, Wed and Thur; Mon and Fri by appointment only."
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "The People Concern",
    "Service Planning/Geographic Area": "SPA 5 - West LA",
    "Operator": "The People Concern",
    "Neighborhood": "Santa Monica",
    "Address": "503 Olympic Blvd, Santa Monica, CA 90401",
    "Website": "https://www.thepeopleconcern.org/",
    "Email": "N/A",
    "Phone": "310-581-9825",
    "Hours of Operation": "Mon-Fri: 10:00am-1:00pm, Sat & Sun: 11:00am-2:00pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A"
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "VOA Pathways ",
    "Service Planning/Geographic Area": "SPA 6 - Central LA",
    "Operator": "VOA Pathways",
    "Neighborhood": "University Park",
    "Address": "3804 Broadway Place, Los Angeles CA",
    "Website": "Lavamae.org",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "Mondays 8:30am-11:30am",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A"
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "Mt Tabor Missionary Baptist Church",
    "Service Planning/Geographic Area": "SPA 6 - Central LA",
    "Operator": "Mt Tabor Missionary Baptist Church ",
    "Neighborhood": "South Los Angeles",
    "Address": "6614 S Western Ave Los Angeles, CA",
    "Website": "Lavamae.org",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "Wednesdays 9am-1pm",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A"
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "Beacon Light Mission- Men's Showers",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Beacon Light Mission",
    "Neighborhood": "Wilmington",
    "Address": "525 Broad Avenue, Wilmington",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "Mon, Thur 8 am",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "Individual Males only"
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "Doors of Hope- Women's Showers",
    "Service Planning/Geographic Area": "SPA 8 - South Bay",
    "Operator": "Doors of Hope",
    "Neighborhood": "Wilmington",
    "Address": "529 Broad Ave., Wilmington , CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "Mondays 8:30am-9:30am",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "Individual Females only"
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "Homeless Resources Fair & Mobile Shower ",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Lava Mae",
    "Neighborhood": "South El Monte",
    "Address": "1201 Loma Avenue, South El Monte, CA 91733 ",
    "Website": "https://lavamae.org/los-angeles/",
    "Email": "N/A",
    "Phone": "(323) 351-7018  ",
    "Hours of Operation": "11:00am - 3:00pm  Every Thursday ",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A"
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "Lario Shower Program",
    "Service Planning/Geographic Area": "SPA 3 - San Gabriel Valley",
    "Operator": "Shower of Hope",
    "Neighborhood": "Duarte",
    "Address": "Lario Staging Area 15701 Foothill Blvd.\rDuarte, CA 91010",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "10:00am - 2:00 pm every Tuesday ",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A"
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "Mental Health America -AVES",
    "Service Planning/Geographic Area": "SPA 1 - Antelope Valley",
    "Operator": "Mental Health America",
    "Neighborhood": "Lancaster",
    "Address": "506 W Jackman St, Lancaster, CA 93534",
    "Website": "https://www.mhalaaves.org/programs_services.php",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "8:00 AM - 5:30 PM Weekdays",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A"
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "Showers",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Calvary Baptist Church",
    "Neighborhood": "Belflower",
    "Address": "14722 Clark Ave., Bellflower, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "Saturday 6:30 AM - 8:00 AM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A"
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "Showers",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "The Lord's Church Clothing Closet",
    "Neighborhood": "Belflower",
    "Address": "9701 Flower St., Bellflower, CA 90706",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "1st and 3rd Wednesday 10:00 AM - 12:00PM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A"
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "Showers",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Cerritos Crossroads Multinational Church",
    "Neighborhood": "Cerritos",
    "Address": "12229 Del Amo Blvd, Cerritos, CA 90703",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "562-809-4143",
    "Hours of Operation": "1st and 3rd Saturday 10:30 AM - 11:30 AM",
    "Walk-Ins Allowed?": "N/A",
    "Eligibility Requirements": "N/A"
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "Showers",
    "Service Planning/Geographic Area": "SPA 7 - South East LA",
    "Operator": "Showers of Hope",
    "Neighborhood": "Whittier",
    "Address": "14181 Telegraph Rd, Whittier, CA",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "N/A",
    "Hours of Operation": "2nd and 3rd Friday 9 AM - 12 PM",
    "Walk-Ins Allowed?": "Yes",
    "Eligibility Requirements": "N/A"
  },
  {
    "Updated by SPA Leadership ": "N/A",
    "Program Name": "Mental Health America",
    "Service Planning/Geographic Area": "SPA 1 - Antelope Valley",
    "Operator": "Mental Health America",
    "Neighborhood": "Lancaster",
    "Address": "506 W Jackman St, Lancaster, CA 93534",
    "Website": "N/A",
    "Email": "N/A",
    "Phone": "(661) 726-2850",
    "Hours of Operation": "9:00 am - 5:00 PM Monday through Friday",
    "Walk-Ins Allowed?": "No",
    "Eligibility Requirements": "Transitioning Age Youth, Family, Adult"
  }
]
