const shower = [
    {
      PROGRAM_NAME: "Showers",
      SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
      OPERATOR : "Union Station Homeless Services",
      NEIGHBORHOOD: "Pasadena",
      ADDRESS: "412 S Raymond Ave Pasadena, CA 91105",
      WEBSITE: "https://unionstationhs.org/",
      EMAIL: "info@unionstationhs.org ",
      PHONE: "(626) 240-4550",
      HOURS_OF_OPERATION: "showers available daily, sign-up at 7am",
      WALK_INS: "Yes",
      ELIGIBILITY_REQUIREMENTS: "N/A"
    },
    {
      PROGRAM_NAME: "Hollywood Adventist Church",
      SERVICE_PLANNING_AREA: "SPA 4 - Metro LA",
      OPERATOR : "Shower of Hope",
      NEIGHBORHOOD: "Hollywood",
      ADDRESS: "1711 N Van Ness Ave, Hollywood 90028",
      WEBSITE: "N/A",
      EMAIL: "N/A",
      PHONE: "N/A",
      HOURS_OF_OPERATION: "Tuesdays: 10:00am–3:00pm",
      WALK_INS: "Yes",
      ELIGIBILITY_REQUIREMENTS: "N/A"
    },
    {
      PROGRAM_NAME: "Hollywood 1st Baptist Church ",
      SERVICE_PLANNING_AREA: "SPA 4 - Metro LA",
      OPERATOR : "Shower of Hope",
      NEIGHBORHOOD: "Hollywood",
      ADDRESS: "6682 Selma Ave Hollywood ",
      WEBSITE: "N/A",
      EMAIL: "N/A",
      PHONE: "N/A",
      HOURS_OF_OPERATION: "Fridays 2:00pm–5:00pm",
      WALK_INS: "Yes",
      ELIGIBILITY_REQUIREMENTS: "N/A"
    },
    {
      PROGRAM_NAME: "Lincoln Heights ",
      SERVICE_PLANNING_AREA: "SPA 4 - Metro LA",
      OPERATOR : "Shower of Hope",
      NEIGHBORHOOD: "Montecito Heights",
      ADDRESS: "3501 Valley Blvd Los Angeles",
      WEBSITE: "N/A",
      EMAIL: "N/A",
      PHONE: "N/A",
      HOURS_OF_OPERATION: "Thursdays: 9:00am–1:00pm",
      WALK_INS: "Yes",
      ELIGIBILITY_REQUIREMENTS: "N/A"
    },
    {
      PROGRAM_NAME: "Cypress Park",
      SERVICE_PLANNING_AREA: "SPA 4 - Metro LA",
      OPERATOR : "Shower of Hope",
      NEIGHBORHOOD: "Downtown Los Angeles",
      ADDRESS: "4212 Poplar St Los Angeles",
      WEBSITE: "N/A",
      EMAIL: "N/A",
      PHONE: "N/A",
      HOURS_OF_OPERATION: "Thursdays: 9:00am–1:00pm",
      WALK_INS: "Yes",
      ELIGIBILITY_REQUIREMENTS: "N/A"
    },
    {
      PROGRAM_NAME: "Boyle Heights (Clinica Romero)",
      SERVICE_PLANNING_AREA: "SPA 4 - Metro LA",
      OPERATOR : "Shower of Hope",
      NEIGHBORHOOD: "Rampart Village",
      ADDRESS: "123 S Alvarado St Los Angeles",
      WEBSITE: "N/A",
      EMAIL: "N/A",
      PHONE: "N/A",
      HOURS_OF_OPERATION: "Fridays: 9:00am–12:00pm",
      WALK_INS: "Yes",
      ELIGIBILITY_REQUIREMENTS: "N/A"
    },
    {
      PROGRAM_NAME: "MacArthur Park",
      SERVICE_PLANNING_AREA: "SPA 4 - Metro LA",
      OPERATOR : "Shower of Hope",
      NEIGHBORHOOD: "Westlake",
      ADDRESS: "2230 W 6th St Los Angeles",
      WEBSITE: "N/A",
      EMAIL: "N/A",
      PHONE: "N/A",
      HOURS_OF_OPERATION: "Fridays: 9:00am–1:00pm",
      WALK_INS: "Yes",
      ELIGIBILITY_REQUIREMENTS: "N/A"
    },
    {
      PROGRAM_NAME: "Highland Park All Saints Church",
      SERVICE_PLANNING_AREA: "SPA 4 - Metro LA",
      OPERATOR : "Shower of Hope",
      NEIGHBORHOOD: "Highland Park",
      ADDRESS: "5619 Monte Vista St Los Angeles",
      WEBSITE: "N/A",
      EMAIL: "N/A",
      PHONE: "N/A",
      HOURS_OF_OPERATION: "Saturdays: 9:00am–1:00pm",
      WALK_INS: "Yes",
      ELIGIBILITY_REQUIREMENTS: "N/A"
    },
    {
      PROGRAM_NAME: "Safe Place for Youth ",
      SERVICE_PLANNING_AREA: "SPA 5 - West LA",
      OPERATOR : "Safe Place for Youth",
      NEIGHBORHOOD: "Venice",
      ADDRESS: "2469 Lincoln Blvd Los Angeles, CA 90291",
      WEBSITE: "N/A",
      EMAIL: "N/A",
      PHONE: "(310) 902-2283",
      HOURS_OF_OPERATION: "Tuesday, Wednesday, Thursday: 1:00pm-5:00pm",
      WALK_INS: "No",
      ELIGIBILITY_REQUIREMENTS: "Walk-Ins welcome Tue, Wed and Thur; Mon and Fri by appointment only."
    },
    {
      PROGRAM_NAME: "The People Concern",
      SERVICE_PLANNING_AREA: "SPA 5 - West LA",
      OPERATOR : "The People Concern",
      NEIGHBORHOOD: "Santa Monica",
      ADDRESS: "503 Olympic Blvd, Santa Monica, CA 90401",
      WEBSITE: "https://www.thepeopleconcern.org/",
      EMAIL: "N/A",
      PHONE: "(310) 581-9825",
      HOURS_OF_OPERATION: "Monday-Friday: 10:00am-1:00pm & Saturday, Sunday: 11:00am-2:00pm",
      WALK_INS: "Yes",
      ELIGIBILITY_REQUIREMENTS: "N/A"
    },
    {
      PROGRAM_NAME: "VOA Pathways ",
      SERVICE_PLANNING_AREA: "SPA 6 - Central LA",
      OPERATOR : "VOA Pathways",
      NEIGHBORHOOD: "University Park",
      ADDRESS: "3804 Broadway Place, Los Angeles CA",
      WEBSITE: "Lavamae.org",
      EMAIL: "N/A",
      PHONE: "N/A",
      HOURS_OF_OPERATION: "Mondays: 8:30am-11:30am",
      WALK_INS: "Yes",
      ELIGIBILITY_REQUIREMENTS: "N/A"
    },
    {
      PROGRAM_NAME: "Mt Tabor Missionary Baptist Church",
      SERVICE_PLANNING_AREA: "SPA 6 - Central LA",
      OPERATOR : "Mt Tabor Missionary Baptist Church ",
      NEIGHBORHOOD: "South Los Angeles",
      ADDRESS: "6614 S Western Ave Los Angeles, CA",
      WEBSITE: "Lavamae.org",
      EMAIL: "N/A",
      PHONE: "N/A",
      HOURS_OF_OPERATION: "Wednesdays:9:00am-1:00pm",
      WALK_INS: "Yes",
      ELIGIBILITY_REQUIREMENTS: "N/A"
    },
    {
      PROGRAM_NAME: "Beacon Light Mission- Men's Showers",
      SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
      OPERATOR : "Beacon Light Mission",
      NEIGHBORHOOD: "Wilmington",
      ADDRESS: "525 Broad Avenue, Wilmington",
      WEBSITE: "N/A",
      EMAIL: "N/A",
      PHONE: "N/A",
      HOURS_OF_OPERATION: "Monday, Thursday: 8:00am-(UNKNOWN)",
      WALK_INS: "Yes",
      ELIGIBILITY_REQUIREMENTS: "Individual Males only"
    },
    {
      PROGRAM_NAME: "Doors of Hope- Women's Showers",
      SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
      OPERATOR : "Doors of Hope",
      NEIGHBORHOOD: "Wilmington",
      ADDRESS: "529 Broad Ave., Wilmington , CA",
      WEBSITE: "N/A",
      EMAIL: "N/A",
      PHONE: "N/A",
      HOURS_OF_OPERATION: "Mondays: 8:30am-9:30am",
      WALK_INS: "Yes",
      ELIGIBILITY_REQUIREMENTS: "Individual Females only"
    },
    {
      PROGRAM_NAME: "Homeless Resources Fair & Mobile Shower ",
      SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
      OPERATOR : "Lava Mae",
      NEIGHBORHOOD: "South El Monte",
      ADDRESS: "1201 Loma Avenue, South El Monte, CA 91733 ",
      WEBSITE: "https://lavamae.org/los-angeles/",
      EMAIL: "N/A",
      PHONE: "(323) 351-7018 ",
      HOURS_OF_OPERATION: "Thursday: 11:00am-3:00pm",
      WALK_INS: "Yes",
      ELIGIBILITY_REQUIREMENTS: "N/A"
    },
    {
      PROGRAM_NAME: "Lario Shower Program",
      SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
      OPERATOR : "Shower of Hope",
      NEIGHBORHOOD: "Duarte",
      ADDRESS: "Lario Staging Area 15701 Foothill Blvd. Duarte, CA 91010",
      WEBSITE: "N/A",
      EMAIL: "N/A",
      PHONE: "N/A",
      HOURS_OF_OPERATION: "Tuesday: 10:00am-2:00pm",
      WALK_INS: "Yes",
      ELIGIBILITY_REQUIREMENTS: "N/A"
    },
    {
      PROGRAM_NAME: "Mental Health America -AVES",
      SERVICE_PLANNING_AREA: "SPA 1 - Antelope Valley",
      OPERATOR : "Mental Health America",
      NEIGHBORHOOD: "Lancaster",
      ADDRESS: "506 W Jackman St, Lancaster, CA 93534",
      WEBSITE: "https://www.mhalaaves.org/programs_services.php",
      EMAIL: "N/A",
      PHONE: "N/A",
      HOURS_OF_OPERATION: "Monday-Friday: 8:00am-5:30pm",
      WALK_INS: "Yes",
      ELIGIBILITY_REQUIREMENTS: "N/A"
    },
    {
      PROGRAM_NAME: "Showers",
      SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
      OPERATOR : "Calvary Baptist Church",
      NEIGHBORHOOD: "Belflower",
      ADDRESS: "14722 Clark Ave., Bellflower, CA",
      WEBSITE: "N/A",
      EMAIL: "N/A",
      PHONE: "N/A",
      HOURS_OF_OPERATION: "Saturday: 6:30am-8:00am",
      WALK_INS: "Yes",
      ELIGIBILITY_REQUIREMENTS: "N/A"
    },
    {
      PROGRAM_NAME: "Showers",
      SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
      OPERATOR : "The Lord's Church Clothing Closet",
      NEIGHBORHOOD: "Belflower",
      ADDRESS: "9701 Flower St., Bellflower, CA 90706",
      WEBSITE: "N/A",
      EMAIL: "N/A",
      PHONE: "N/A",
      HOURS_OF_OPERATION: "1st and 3rd Wednesday of every Month: 10:00am-12:00pm",
      WALK_INS: "Yes",
      ELIGIBILITY_REQUIREMENTS: "N/A"
    },
    {
      PROGRAM_NAME: "Showers",
      SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
      OPERATOR : "Cerritos Crossroads Multinational Church",
      NEIGHBORHOOD: "Cerritos",
      ADDRESS: "12229 Del Amo Blvd, Cerritos, CA 90703",
      WEBSITE: "N/A",
      EMAIL: "N/A",
      PHONE: "(562) 809-4143",
      HOURS_OF_OPERATION: "1st and 3rd Saturday of every Month: 10:30am-11:30am",
      WALK_INS: "N/A",
      ELIGIBILITY_REQUIREMENTS: "N/A"
    },
    {
      PROGRAM_NAME: "Showers",
      SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
      OPERATOR : "Showers of Hope",
      NEIGHBORHOOD: "Whittier",
      ADDRESS: "14181 Telegraph Rd, Whittier, CA",
      WEBSITE: "N/A",
      EMAIL: "N/A",
      PHONE: "N/A",
      HOURS_OF_OPERATION: "2nd and 3rd Friday of every Month: 9:00am-12:00pm",
      WALK_INS: "Yes",
      ELIGIBILITY_REQUIREMENTS: "N/A"
    },
    {
      PROGRAM_NAME: "Mental Health America",
      SERVICE_PLANNING_AREA: "SPA 1 - Antelope Valley",
      OPERATOR : "Mental Health America",
      NEIGHBORHOOD: "Lancaster",
      ADDRESS: "506 W Jackman St, Lancaster, CA 93534",
      WEBSITE: "N/A",
      EMAIL: "N/A",
      PHONE: "(661) 726-2850",
      HOURS_OF_OPERATION: "Monday-Friday: 9:00am-5:00pm",
      WALK_INS: "No",
      ELIGIBILITY_REQUIREMENTS: "Transitioning Age Youth, Family, Adult"
    }
]

