const subAbuse = [[
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
    OPERATOR: "American Recovery Center ",
    NEIGHBORHOOD: "Pomona",
    ADDRESS: "2180 West Valley Boulevard Pomona CA 91768",
    WEBSITE: "N/A",
    PHONE: "(909) 865-2336",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
    OPERATOR: "American Recovery Center ",
    NEIGHBORHOOD: "Long Beach",
    ADDRESS: "1334 Alamitos Ave Long Beach, CA 90813",
    WEBSITE: "N/A",
    PHONE: "(562) 218-2355",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
    OPERATOR: "American Recovery Center ",
    NEIGHBORHOOD: "Pasadena",
    ADDRESS: "56 W. Del Mar Blvd. Pasadena, CA 91105",
    WEBSITE: "N/A",
    PHONE: "(626) 577-4649",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 5 - West LA",
    OPERATOR: "American Recovery Center ",
    NEIGHBORHOOD: "Santa Monica",
    ADDRESS: "1658 11th St Santa Monica, CA 90404",
    WEBSITE: "N/A",
    PHONE: "(310) 450-7235",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 2 - San Clarita Valley",
    OPERATOR: "American Recovery Center ",
    NEIGHBORHOOD: "Canoga Park",
    ADDRESS: "21375 Roscoe Blvd. Canoga Park, CA 91304",
    WEBSITE: "N/A",
    PHONE: "(818) 883-5527",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
    OPERATOR: "Salvation Army- Bell Shelter",
    NEIGHBORHOOD: "Bell",
    ADDRESS: "5600 Richenbacker Rd. Bldg 2A-2B Bell, CA 90201",
    WEBSITE: "N/A",
    PHONE: "(323) 263-1206 ",
    HOURS_OF_OPERATION: "Call Mon – Fri at 9:00 a.m",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "Referral perferred"
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 4 - Metro LA",
    OPERATOR: "N/A",
    NEIGHBORHOOD: "Rampart Village",
    ADDRESS: "155 South Bimini Place Los Angeles, California 90004",
    WEBSITE: "N/A",
    PHONE: "(213) 388-5423",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "Long Term ResidentialSliding Scale"
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
    OPERATOR: "Aurora Behavioral Health Care- Charter Oak",
    NEIGHBORHOOD: "Covina",
    ADDRESS: "1161 E. Covina Blvd Covina, CA 91724",
    WEBSITE: "https://www.charteroakhospital.com/",
    PHONE: "(626) 996-1632",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "N/A",
    OPERATOR: "First House",
    NEIGHBORHOOD: "N/A",
    ADDRESS: "N/A",
    WEBSITE: "N/A",
    PHONE: "(949) 515-2360",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "No Further information "
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 5 - West LA",
    OPERATOR: "Clare Foundation",
    NEIGHBORHOOD: "Santa Monica",
    ADDRESS: "909 Pico Blvd, Santa Monica, CA 90405",
    WEBSITE: "https://clarefoundation.org/",
    PHONE: "(310) 314-6245",
    HOURS_OF_OPERATION: "24 Hours",
    WALK_INS: "Yes",
    ELIGIBILITY_REQUIREMENTS: "Call to schedule an appointment ",
    NOTES: "No Further information "
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
    OPERATOR: "N/A",
    NEIGHBORHOOD: "Norwalk",
    ADDRESS: "11401 Bloomfield Avenue Buildings 209, 211 and 313 Norwalk CA 90650",
    WEBSITE: "https://www.intherooms.com/Rehabs/CA/Norwalk/Southern_CA_Alcohol_and_Drug_Progs_Inc_1069.php",
    PHONE: "(562) 864-7724",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "Didi Hirsch CMHC Via Avanta Program",
    SERVICE_PLANNING_AREA: "SPA 2 - San Clarita Valley",
    OPERATOR: "Didi Hirsch Mental Health",
    NEIGHBORHOOD: "Pacoima",
    ADDRESS: "11643 Glenoaks Blvd. Pacoima, CA 91331",
    WEBSITE: "https://didihirsch.org/",
    PHONE: "(818) 897-2609 ",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
    OPERATOR: "Grandview Foundation",
    NEIGHBORHOOD: "Pasadena",
    ADDRESS: "1230 N Marengo Ave Pasadena, CA 91114",
    WEBSITE: "https://grandviewfoundation.com/",
    PHONE: "(626) 797-1124",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "Call for intake process"
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 6 - Central LA",
    OPERATOR: "His Sheltering Arms",
    NEIGHBORHOOD: "South Los Angeles",
    ADDRESS: "11101 S Main St Los Angeles, CA 90061",
    WEBSITE: "N/A",
    PHONE: "(323) 755-6646",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 2 - San Clarita Valley",
    OPERATOR: "People in Progress Sun Valley Community Rehab Center",
    NEIGHBORHOOD: "Sun Valley",
    ADDRESS: "8140 Sunland Boulevard Sun Valley CA 91352",
    WEBSITE: "N/A",
    PHONE: "(818) 768-7494",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 4 - Metro LA",
    OPERATOR: "Rena B. Recovery Center",
    NEIGHBORHOOD: "East Hollywood",
    ADDRESS: "4445 Burns Ave, Los Angeles, CA 90029",
    WEBSITE: "N/A",
    PHONE: "(323) 664-8940",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "100 beds, Call for Intake Process"
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 4 - Metro LA",
    OPERATOR: "Royal Palms Recovery Center (Albert)",
    NEIGHBORHOOD: "Historic Filipinotown",
    ADDRESS: "360 S Westlake Ave, Los Angeles, CA 90057",
    WEBSITE: "N/A",
    PHONE: "N/A",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "(135 beds), Call for intake process"
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
    OPERATOR: "River Community Recovery",
    NEIGHBORHOOD: "Azuza",
    ADDRESS: "23701 E Fork Rd, Azusa, CA 91702",
    WEBSITE: "http://losangeles.networkofcare.org/mh/services/agency.aspx?pid=SOCIALMODELRECOVERYSYSTEMSTHERIVERCOMMUNITYAZUSA_68_2_0",
    PHONE: "(626) 910.-1202",
    HOURS_OF_OPERATION: "MON - FRI 9:00 AM - 5:00 PM",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
    OPERATOR: "Substance Abuse Foundation",
    NEIGHBORHOOD: "Long Beach",
    ADDRESS: "3125 E 7th St Long Beach CA 90804",
    WEBSITE: "http://asaferefuge.org/",
    PHONE: "(562) 987-5742",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 2 - San Clarita Valley",
    OPERATOR: "Tarzana Treatment Center",
    NEIGHBORHOOD: "Tarzana",
    ADDRESS: "18646 Oxnard St Tarzana, CA",
    WEBSITE: "https://www.tarzanatc.org/",
    PHONE: "(800) 996-1051",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "N/A",
    OPERATOR: "Red Gate ",
    NEIGHBORHOOD: "N/A",
    ADDRESS: "N/A",
    WEBSITE: "N/A",
    PHONE: "(562) 599-8444",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "No further information "
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 4 - Metro LA",
    OPERATOR: "Volunteers Of America Detox (Drop in Center)",
    NEIGHBORHOOD: "Downtown Los Angeles",
    ADDRESS: "543 Crocker St Los Angeles, CA 90013",
    WEBSITE: "https://voala.org/",
    PHONE: "(213) 236-0874",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 4 - Metro LA",
    OPERATOR: "Walden House Transitional Treatment Center",
    NEIGHBORHOOD: "Fashion District",
    ADDRESS: " 1355 South Hill Street Los Angeles CA 90015",
    WEBSITE: "N/A",
    PHONE: "(213) 763-6220",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 3 - San Gabriel Valley",
    OPERATOR: "Walter Hoving Home",
    NEIGHBORHOOD: "Pasadena",
    ADDRESS: "127 S El Molino Ave nPasadena, CA 91101",
    WEBSITE: "https://hovinghome.org/",
    PHONE: "(626) 405-0950",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "Warm Springs Rehabilitation Center",
    SERVICE_PLANNING_AREA: "SPA 2 - San Clarita Valley",
    OPERATOR: "Antelope Valley Rehabilitation Centers",
    NEIGHBORHOOD: "Castaic",
    ADDRESS: "38200 North Lake Hughes Road Castaic CA 91310",
    WEBSITE: "N/A",
    PHONE: "(661) 257-2342",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "N/A",
    SERVICE_PLANNING_AREA: "SPA 4 - Metro LA",
    OPERATOR: "Weingart Center",
    NEIGHBORHOOD: "Downtown Los Angeles",
    ADDRESS: "566 South San Pedro Street Los Angeles, CA 90013",
    WEBSITE: "N/A",
    PHONE: "(213) 627-9000.",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "Exodus Recovery, Inc.",
    SERVICE_PLANNING_AREA: "SPA 8 - South Bay",
    OPERATOR: "Exodus Recovery, Inc.",
    NEIGHBORHOOD: "Redondo Beach",
    ADDRESS: "923 South Catalina Avenue Redondo Beach, CA, 90277",
    WEBSITE: "N/A",
    PHONE: "800-286-1182",
    HOURS_OF_OPERATION: "Monday through Friday 9:00 a.m. to 5:00 p.m",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "ages of 26-59 only",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "Drug and Alcohol Program",
    SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
    OPERATOR: "Positive Steps",
    NEIGHBORHOOD: "Downey",
    ADDRESS: "11501 Dolan Ave., Downey, CA 90241",
    WEBSITE: "N/A",
    PHONE: "562-923-7894",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "Alcohol and drug programs for men"
  },
  {
    PROGRAM_NAME: "Drug and Alcohol Program",
    SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
    OPERATOR: "Little House",
    NEIGHBORHOOD: "Bellflower",
    ADDRESS: "9718 Harvard St., Bellflower, CA 90706",
    WEBSITE: "N/A",
    PHONE: "562-925-2777",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "Recovery home for women with substance abuse"
  },
  {
    PROGRAM_NAME: "Substance abuse program",
    SERVICE_PLANNING_AREA: "SPA 7 - South East LA",
    OPERATOR: "Los Angeles Center for Alcohol and Drug Abuse",
    NEIGHBORHOOD: "Santa Fe Springs",
    ADDRESS: "11015 Bloomfield Ave, Santa Fe Springs, CA 90670",
    WEBSITE: "http://www.lacada.com/",
    PHONE: "562-906-2676",
    HOURS_OF_OPERATION: "N/A",
    WALK_INS: "N/A",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "LA County Dept. of Mental Health",
    SERVICE_PLANNING_AREA: "SPA 1 - Antelope Valley",
    OPERATOR: "LACDMH",
    NEIGHBORHOOD: "Palmdale",
    ADDRESS: "1529 E. Palmdale Blvd., Ste. 150 Palmdale, CA 93550",
    WEBSITE: "dmh.lacounty.gov",
    PHONE: "(800) 854-7771",
    HOURS_OF_OPERATION: "Monday through Sunday, 24 hours per day",
    WALK_INS: "Yes",
    ELIGIBILITY_REQUIREMENTS: "Transitioning Age Youth, Family, Adult",
    NOTES: "N/A"
  },
  {
    PROGRAM_NAME: "Tarzana Treatment Center",
    SERVICE_PLANNING_AREA: "SPA 1 - Antelope Valley",
    OPERATOR: "Tarzana Treatment Center",
    NEIGHBORHOOD: "Lancaster",
    ADDRESS: "44447 10th St W, Lancaster, CA 93534",
    WEBSITE: "N/A",
    PHONE: "(661) 726-2630",
    HOURS_OF_OPERATION: "Monday - Friday 8:00 AM - 5:00 PM",
    WALK_INS: "No",
    ELIGIBILITY_REQUIREMENTS: "N/A",
    NOTES: "N/A"
  }]]